### ISSUE TITLE
Maybe enable insertHintOnTab feature

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#106]
In the list of preferences for Brackets, one that's turned off, but might be useful for us to enable is `insertHintOnTab`.  What it does is insert the currently selected code hint when the tab key is pressed.

My vote is that we should enable this.  Can people try turning it on/off and see what they think?

**Comment by sedge** [comment]
This is a great feature. I'm with you on this.

**Comment by humphd** [comment]
See https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences for the complete list.

**Comment by humphd** [comment]
Fixed by https://github.com/humphd/brackets-browser-livedev/pull/35
