### ISSUE TITLE
Deal with 404s in filer-dialogs extension

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#113]
![screen shot 2015-03-18 at 12 31 25 pm](https://cloud.githubusercontent.com/assets/427398/6713740/cc5dd64a-cd6a-11e4-88e6-5ed16b8b0f98.png)

The [filer-dialogs extension](https://github.com/ScottDowne/filer-dialogs) adds File > Open and File > Save As dialogs for our filer filesystem.  It needs a build step to install fonts from font-awesome using `bower`.  We don't have that in our Gruntfile, so our `dist/` is missing those CSS files.  Also, we probably aren't copying them over properly.

This should get fixed.

**Comment by sedge** [comment]
Do we want to remove fontawesome completely?

**Comment by humphd** [comment]
Well, we are now using it for the gutter icon in HTMLHinter.  So I say we start by making this work.  Can we do this in such a way that we make sure we only load it once?  And only load the smallest set of what is needed for our icon use?  Keep an eye on overall size increases.

**Comment by gideonthomas** [comment]
Seems like HTMLHinter is going to be using an image instead!

**Comment by humphd** [comment]
This is fixed now, can we close? @gideonthomas

**Comment by gideonthomas** [comment]
Well, I don't think this is technically fixed. It just doesn't show up anymore because we stopped using filer-dialogs in humphd/brackets@9929a0cca25275fe4e2278e42f28e22e60e9c8c9
