### ISSUE TITLE
Error when trying to use an iframe tag.

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#114]
![screen shot 2015-03-18 at 2 32 54 pm](https://cloud.githubusercontent.com/assets/9154982/6716417/c39d296e-cd7b-11e4-8735-eb04a48254b7.png)
This error shows up when trying to use the iframe tag.

**Comment by humphd** [comment]
That's not our code, but rather Github not allowing you to "click jack" their code by putting it in an iframe.  See http://en.wikipedia.org/wiki/Clickjacking.  Try another domain.  Lots of big sites will block this.

**Comment by KeniMorri** [comment]
Ye, try a site that doesn't disallow clickjacking like, 

    <iframe src="http://www.w3schools.com">
      <p>Your browser does not support iframes.</p>
    </iframe>

**Comment by AJDBenner** [comment]
I see, w3schools seems to work. I'll close this.
