### ISSUE TITLE
Split NoHostServer into two servers: HTMLServer and StaticServer

### ISSUE THREAD

**Issue by K-LV** [humphd/brackets#115]
Things to do:

* Register both servers with different Priorities 9001, 9000, such that HTMLServer.js tries first to serve a file, then StaticServer.js gets it in brackets-browser-livedev/main.js ~L150.  This will involve rewriting _getServer so it works for the two different servers.

    Look at servers in https://github.com/adobe/brackets/tree/master/src/LiveDevelopment/Servers

    HTMLServer.js --> brackets-browser-livedev/nohost/HTMLServer.js

* Add code to overload canServe() method in BaseServer like so https://github.com/adobe/brackets/blob/master/src/extensions/default/StaticServer/StaticServer.js#L72 to check if this is an HTML file or not (we'll only serve if it is).

* Everything else is same for making the livedoc, i.e., we need to do what maybeServeLiveDoc is doing now, and give back a rewritten blob of the editor contents vs. what's on disk.

    StaticServer.js --> brackets-browser-livedev/nohost/StaticServer.js

    We don't need to override canServe(), meaning it will always be true

    We need to server blobs using Filer.blobs[filename] for css, js, and other external resource files.

    Launcher.prototype.launch(url)

 * We probably need to inspect the filename/url we are given, and deal with .html type files vs. other resources, serving from the appropriate server above in both cases. Only one of which will create a livedoc, the other will just serve the blob url untouched. 

* The launcher can be simplified such that we just use the URL we are passed to launch(url), and the server will have already created a BLOB for us (i.e., we don't have to do server.maybeServeLiveDoc(...) etc).  We should be able to just do browser.update(url).

**Comment by humphd** [comment]
We also need to rework how we do `urlToPath` and `pathToUrl` in our servers.  This is where we should be using the blob's we create in Filer.  Probably we'll still need one special case for getting the instrumented HTML asynchronously.

**Comment by humphd** [comment]
I've split this bug into 5 other bugs to make it easier to work on this in stages.  I'm going to close this bug in place of those.
