### ISSUE TITLE
Indentation looks incorrect on the <tr> tag 

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#117]
When you make the &lt;tr&gt; tag within a table, the auto indentation seems to be incorrect when you hit enter to move the &lt;/tr&gt; tag to the next line.
![screen shot 2015-03-19 at 11 02 22 am](https://cloud.githubusercontent.com/assets/9154982/6733427/9572f6e2-ce28-11e4-8718-4cacf29bc227.png)

**Comment by humphd** [comment]
Is this known/filed on Brackets upstream?  What happens in desktop Brackets 1.2?

**Comment by AJDBenner** [comment]
It looks like this issue happens on desktop Brackets 1.2, I haven't been able to find this issue filed in Brackets.

**Comment by sedge** [comment]
@AJDBenner If you can isolate a simple set of STR (steps to reproduce) then you should file it upstream.

**Comment by KeniMorri** [comment]
The basic premise of this issue is, when you make a <table> tag with autocomplete, it creates </table> after your cursor, so when you go to press enter, it puts u in the same column as <table> so:

    <table>
    </table>

thus when you start typing out <tr> you'll be here:

    <table>
    <tr></tr></table>

then when you press enter between the <tr> tag it'll end up looking like this:

    <table>
    <tr>
        </tr></table>

It seems it might be upstreamable, they could basically just try to detect that you pressed enter within an empty <table> tag, not sure how complicated that'd be

**Comment by AJDBenner** [comment]
This issue has been filed upstream https://github.com/adobe/brackets/issues/10770.
Here's a better representation of the issue.

![demo2](https://cloud.githubusercontent.com/assets/9154982/6754254/cdc46ca0-cef1-11e4-8246-8914a7aba260.gif)

**Comment by AJDBenner** [comment]
peterflynn took a look at this bug upstream and said it's a bug/missing feature in CodeMirror. He also said it's expected that the opening `<tr>` tag is expected to be indented like this.
```
<table>
    <tr>
    </tr>
</table>
```

**Comment by humphd** [comment]
Do you want to see if it's filed upstream with CodeMirror and file if not?

On Mar 22, 2015 7:57 PM, Andrew Benner <notifications@github.com> wrote:

peterflynn took a look at this bug upstream and said it's a bug/missing feature in CodeMirror. He also said it's expected that the opening <tr> tag is expected to be indented like this.

<table>
    <tr>
    </tr>
</table>

**Comment by AJDBenner** [comment]
This issue is filed in the CodeMirror repo as well https://github.com/codemirror/CodeMirror/issues/3147

**Comment by AJDBenner** [comment]
I was directed to test this issue [here](http://codemirror.net/demo/closetag.html) and it doesn't seem to reproduce in codemirror/CodeMirror. This could possibly be that adobe Brackets instance of CodeMirror is pointing to an old commit.

**Comment by AJDBenner** [comment]
https://github.com/humphd/brackets-browser-livedev/pull/40 fixes this issue.
