### ISSUE TITLE
Console error when editing CSS using the inline CSS widget

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#118]
If you open the inline CSS widget for a HTML element with CSS applied to it and edit the CSS in the widget you get this console error.
![screen shot 2015-03-19 at 4 17 59 pm](https://cloud.githubusercontent.com/assets/9154982/6740061/98859788-ce53-11e4-84dd-cc15ecc8a26a.png)
![screen shot 2015-03-19 at 4 18 42 pm](https://cloud.githubusercontent.com/assets/9154982/6740076/ae34b9f6-ce53-11e4-88dd-0ab045e2edd0.png)

**Comment by humphd** [comment]
My strong suspicion is that we're running this through the slowparse/htmlhint stuff, and the DOM is different enough to cause things to break.  Can you try disabling the HTMLHint extension and see if you can reproduce?

**Comment by AJDBenner** [comment]
When reproducing this error with HTMLHinter turned off you still receive the "data-brackets-id=1 not found" error

**Comment by sedge** [comment]
@AJDBenner Does that cause any functionality to break?

**Comment by humphd** [comment]
That's *probably* another issue related to things moving around in the preview DOM, and not finding elements to highlight--I wouldn't read it as part of the other error.  Note, too, that in your screenshot above, the errors are coming from two different pages: the `errorDisplay.js` is in the editor, and the other ones are within a blob URL, meaning it's running in the preview.

So eliminating the HTMLHint makes this go away?

**Comment by AJDBenner** [comment]
Eliminating the HTMLHint makes the "Uncaught TypeError" go away, but the "data-brackets-id=1 not found" error still remains. It doesn't seem to break anything in the live preview though.

**Comment by AJDBenner** [comment]
Actually, I'm mistaken. After changing the CSS in the widget, if you close the widget and click on the &lt;p&gt; tag element this error is displayed.

![screen shot 2015-03-20 at 10 09 55 am](https://cloud.githubusercontent.com/assets/9154982/6753005/52187a04-cee9-11e4-9e2a-87341009f5ed.png)

If you try to change the content within the &lt;p&gt; tag after this error the live preview is broken and displays this error.

![screen shot 2015-03-20 at 10 12 41 am](https://cloud.githubusercontent.com/assets/9154982/6753065/b6f0bdb0-cee9-11e4-86f7-be4838bdf6c2.png)

**Comment by humphd** [comment]
Moving out of PPP

**Comment by AJDBenner** [comment]
This issue is filed upstream, but it seems to act differently with upstream than with Bramble. https://github.com/adobe/brackets/issues/10773

**Comment by K-LV** [comment]
@AJDBenner I can't get this error to reproduce in our latest bramble code. Can you confirm?

**Comment by AJDBenner** [comment]
It still reproduces for me. 

STR:
- add style to `<p> tag` like this `<style>p {color: red; }</style>`
- push CMD + E
- change the color using the inline widget
- click in the `<p> tag` and change the content

**Comment by K-LV** [comment]
I see. I was testing using an external style sheet. So it appears the issue is only present using internal CSS.

**Comment by AJDBenner** [comment]
I have filed this bug upstream https://github.com/adobe/brackets/issues/10773

**Comment by sedge** [comment]
This is no longer occuring.
