### ISSUE TITLE
Write extension for context sensitive help

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#12]
Thimble.webmaker.org gives technical advice about HTML elements, CSS selectors and CSS properties explaining their function and where to use them. When the editor's cursor is touching something it can advise on (e.g. ![screen shot 2015-01-26 at 11 35 25 am](https://cloud.githubusercontent.com/assets/1616860/5903407/773c4248-a54f-11e4-99ff-4a76d9f34584.png) or ![screen shot 2015-01-26 at 11 36 20 am](https://cloud.githubusercontent.com/assets/1616860/5903421/9683b53c-a54f-11e4-82a8-c9f8354c73fb.png)) an icon (![screen shot 2015-01-26 at 11 39 00 am](https://cloud.githubusercontent.com/assets/1616860/5903478/efbdfc48-a54f-11e4-9ebb-2904333eecd5.png)) appears on the opposite side of the gutter that can be clicked on to show help:

--------------------------------
![screen shot 2015-01-26 at 11 41 00 am](https://cloud.githubusercontent.com/assets/1616860/5903543/46aa1ece-a550-11e4-8cdf-822b53aa8fe7.png)

--------------------------------

We need an extension that will provide this functionality.

**Comment by sedge** [comment]
@humphd Do we care about this at all? I know Moz might, but if we don't I'll close this issue.

**Comment by humphd** [comment]
I think we can push this out of the MVP.  Can you get a milestone for Feb 20th going and just leave this out of it.

**Comment by sedge** [comment]
see #320 for the latest on this issue.
