### ISSUE TITLE
Filesystem should automatically create/manage BLOB URLs, LiveDocuments for files

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#121]
Splitting off from #115, this bug is about adding a new responsibility to the filesystem for keeping BLOB URLs in sync with file writes, deletes, renames, etc.  The goal is to allow synchronous access to BLOB URLs for a given path, which means maintaining a cache for these on every filesystem write (since accessing the data blocks is always asynchronous).

The Brackets Filesystem needs to hold a reference to a module that maintains a BLOB URL cache which is keyed on both path and URL, in order to support the `pathToUrl(path)` and `urlToPath(url)` calls in LiveDev servers.

I suspect that we'll have to be careful about how we deal with updates to files and BLOB URLs changing.  In a regular web server, URLs to a file are stable between writes (i.e., foo.com/index.html is going to be the right URL no matter if you update the index.html file on disk).  With BLOB URLs, we'll be generating new ones every time, invalidating old ones.  However the LiveDev stuff may need to lookup a path based on an old URL, so we should maintain links to paths for old BLOB URLs (i.e., don't delete them when we update)

Other things we have to deal with are Filesystem methods like `unlink`, `moveToTrash` and `rename`, which will affect the synchronization of the cache.

**Comment by humphd** [comment]
One improvement to my pseudo-code I wrote earlier this week, where I was suggesting we do `Filer.blobs`.  That's not a great idea, because it's not tied to an instance.  We should put the public facing API for accessing these blobs on the `fs` instance somehow.

**Comment by humphd** [comment]
See discussion in https://github.com/humphd/brackets-browser-livedev/pull/37/files#r26865304--I think we also want to manage LiveDocuments for HTML files when we write them.

**Comment by K-LV** [comment]
Related to this [PR] (https://github.com/humphd/brackets/pull/92/files).

**Comment by K-LV** [comment]
@gideonthomas says that he will take on finishing this up

**Comment by humphd** [comment]
@gideonthomas one thing to note when you are doing this work, I realize that I never used `URL.revokeObjectURL()` to clean up dead BLOB URLs, see https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL

Probably we should do that when we delete them from the cache.
