### ISSUE TITLE
Figure out why certain file types do not work with img tag on hover event

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#122]
Presently with the `<img>` tag in relation to hovering over the src, there are certain file types that don't presently appear to work, these being:

bmp
no file type(extension)
tiff(but it doesn't appear to be a web file format, so neglect able I imagine)

The following are presently working:

svg
jpg
jpeg
png
gif

**Comment by humphd** [comment]
There's a possible way to hack this upstream to make it work for any URL.  It involves programmatically trying to assign a URL to an `img` element's `src`, and listening for `onload` and `onerror`:

```js
var img = document.createElement('img');
img.onload = function() {
  // url points to an image and can be loaded, display pop-up
};
img.onerror = function() {
  // url points to a non-image, and can't be loaded, don't display.
};
img.src = url;
```
I'd look in Brackets' upstream issues and see if this is filed already.

**Comment by humphd** [comment]
I filed https://github.com/adobe/brackets/issues/10786 upstream.

**Comment by humphd** [comment]
I got sick of waiting for this to land upstream, so I've just landed it on our fork.  Closing.
