### ISSUE TITLE
Cannot open helpful links within the HTMLHinter 

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#128]
When an error like this is displayed

![screen shot 2015-03-20 at 1 42 24 pm](https://cloud.githubusercontent.com/assets/9154982/6757397/1cf18096-cf07-11e4-9f51-5915c095d4cb.png)

The user is unable to click the link to be redirected to a list of CSS properties. This error message shows in the console.

![screen shot 2015-03-20 at 1 42 49 pm](https://cloud.githubusercontent.com/assets/9154982/6757422/440ccd52-cf07-11e4-98ab-aff242fabfd6.png)

The user is also unable to right click on the link to open in a new tab. Is there a way around this to allow a right click to open the link in a new tab?

**Comment by humphd** [comment]
It's probably just that we need to implement opening a link in a new tab here:

https://github.com/humphd/brackets/blob/bramble/src/thirdparty/browser-appshell.js#L74-L79

**Comment by gideonthomas** [comment]
@AJDBenner you can take this bug if you want

**Comment by AJDBenner** [comment]
https://github.com/humphd/brackets/pull/135 fixes this issue.
