### ISSUE TITLE
HintHinter Gutter too large, and bubble looks odd in Large Text Mode

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#129]
Presently the current HTML Hinter has a few very marginal issues expressed in picture below:

![untitled](https://cloud.githubusercontent.com/assets/1750230/6758329/b3f84ce4-cf0d-11e4-900b-7a2948513c68.png)

The gutter has increased in size leaving the user with less space to code in and the current Bubble looks weird in Large Text mode.

**Comment by AJDBenner** [comment]
https://github.com/KeniMorri/HTMLHinter/pull/6 will fix this issue.
