### ISSUE TITLE
HTMLHinter Error Finding oddity

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#131]
Presently if you break a > on the beginning tag of a pair, then break tags above it, then fix the original tag the highlighting remains

![untitled](https://cloud.githubusercontent.com/assets/1750230/6758572/6e56e950-cf0f-11e4-9e03-ebfdb98737bf.gif)

**Comment by humphd** [comment]
I *think* the fix @gideonthomas is doing in #127 will fix this.  Please confirm with his patch.

**Comment by KeniMorri** [comment]
Fixed in latest update to HTMLHinter
