### ISSUE TITLE
Brackets Extensions do not load within browser

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#14]
Problem: Extensions do not appear to work in browser

Explaination: When running brackets with "python -m SimpleHTTPServer" or live-server, extensions within the browser do not appear to load.
To compound upon this, when trying to access the Extension Manager we receive this error:
![screenshot 2015-01-26 12 54 19](https://cloud.githubusercontent.com/assets/1750230/5905064/4172c464-a55b-11e4-9115-d2bfa3b954dd.png)

**Comment by humphd** [comment]
Extensions do work in the browser, but you have to bundle them properly, and tell it to load them by default.  Take a look at how the makedrive-sync-icon extension works in my bramble branch.

**Comment by KeniMorri** [comment]
guess I should have asked on irc first, my bad

**Comment by humphd** [comment]
Also note: we'll never be able to get the Extension Manager to work, since it will want to talk to a server we don't host, and we'll have cross-origin issues using XHR.  Probably we only want to worry about default/bundled extensions vs. user installed.

**Comment by KeniMorri** [comment]
alright, I'll look into it, thanks.
