### ISSUE TITLE
Figure out why Brackets Line Numbers Gutter is so large

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#141]
Presently Brackets code mirror gutter has 50px of bloat:
![screenshot 2015-03-26 02 40 31](https://cloud.githubusercontent.com/assets/1750230/6841498/005c7d50-d362-11e4-927c-008d5894f137.png)

From reading comments around the code I've found out the partial reasoning behind this seems to be that making the gutter any smaller breaks the code mirror instance, shown here:
![screenshot 2015-03-26 02 40 18](https://cloud.githubusercontent.com/assets/1750230/6841504/1bc633f6-d362-11e4-9002-63d0a8e8337a.png)

**Comment by gideonthomas** [comment]
Fixed with 09e0913e93c84a4c45274b7988ec2fb4a3d85eb0
