### ISSUE TITLE
Change content of new HTML files to not be empty.

### ISSUE THREAD

**Issue by K-LV** [humphd/brackets#143]
Right now, when you create a new HTML document, the content of that new file is empty. This leads to problems when trying to preview it. This solution is to intercept the writing process of HTML files and change the contents to a default page.

**Comment by humphd** [comment]
Make sure we put documentation about why we're doing this  (e.g., because we always preview docs immediately in LiveDev) in the code that does this.

**Comment by gideonthomas** [comment]
Fixed with 155a8620b371f05624b527925064c73f351661b7
