### ISSUE TITLE
Spacing is incorrect on <html> tag when using autocomplete.

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#144]
This is what happens when you hit enter to autocomplete.

![demo](https://cloud.githubusercontent.com/assets/9154982/6853090/2a7876ae-d3bf-11e4-951b-f0eb9ba0859b.gif)

This is what happens when you hit tab to autocomplete.

![demo](https://cloud.githubusercontent.com/assets/9154982/6853110/602ca874-d3bf-11e4-93d7-798e25ffe2ad.gif)

This error doesn't happen in desktop Brackets.

**Comment by AJDBenner** [comment]
This issue doesn't occur if `<!doctype html>` is declared.

**Comment by humphd** [comment]
I'm not sure this is a big deal.  I'd WONTFIX this, personally.
