### ISSUE TITLE
Investigate new ways in order to display HTMLHinter Hint

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#148]
Presently we spawn a second gutter to the left of the line numbers gutter, this current method wastes a lot of horizontal space which is very important when it comes to our web implementation of brackets due to space wasted on the preview. This problem is refactored further if we consider that we do not know how the user will use our application.

Possible Solutions:
1. Override the Gutter in relation to the line in which an error shows up so that we don't need to spawn a new gutter

2. User the Vertical Scroll bar method inside code mirror to spawn the icon, this method is currently used in thimble so it should not be difficult to implement
![screenshot 2015-03-27 13 56 28](https://cloud.githubusercontent.com/assets/1750230/6873790/18fc0fb0-d489-11e4-80d9-dfd61d386a55.png)

**Comment by humphd** [comment]
https://github.com/KeniMorri/HTMLHinter/pull/8 is fixing this, which I am hoping we'll get in today.

**Comment by humphd** [comment]
This just needs to land via submodule update in bramble.  Leaving open til then.
