### ISSUE TITLE
Thimble is broken

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#153]
Reported by @KeniMorri and @K-LV 
![screen shot 2015-03-30 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/5816130/6905329/3142f354-d6f5-11e4-8a66-7b95cd24921e.png)
 is shown when we  try to load thimble locally which uses whatevers on brackets:bramble

Seems like Thimble is not passing the "bramble:init" postMessage to brackets-browser-livedev which is why it never fulfils it's initExtension promise which is why it times out.

**Comment by gideonthomas** [comment]
The problem starts with [this](https://github.com/sedge/thimble.webmaker.org/commit/7b2c8d2913fc117fcf616edf7cfea6407545b50a) commit which allows thimble to use brackets from another domain

**Comment by humphd** [comment]
Paging @sedge...is this just locally or upstream too?  NOTE you need to update your .env locally to get the right domains.

**Comment by humphd** [comment]
https://github.com/sedge/thimble.webmaker.org/commit/b63ece9ec6287694ee65c05fe21e39c3e9d575ff#diff-bb503f3d9047bcd4a5730559f1e16560R36 should be made smarter to know about port details, too.  Question, why are we doing this parsing at all?  Why not have different configs for different scenarios?

**Comment by humphd** [comment]
https://github.com/sedge/thimble.webmaker.org/commit/b63ece9ec6287694ee65c05fe21e39c3e9d575ff#diff-bb503f3d9047bcd4a5730559f1e16560R36 should be made smarter to know about port details, too.  Question, why are we doing this parsing at all?  Why not have different configs for different scenarios?

**Comment by humphd** [comment]
https://github.com/sedge/thimble.webmaker.org/commit/b63ece9ec6287694ee65c05fe21e39c3e9d575ff#diff-bb503f3d9047bcd4a5730559f1e16560R36 should be made smarter to know about port details, too.  Question, why are we doing this parsing at all?  Why not have different configs for different scenarios?

**Comment by sedge** [comment]
Let's do different configs - one for the origin that serves bramble and another for where the submodule is being served from.

It's the difference between `someorigin.com` and `someorigin.com/subroute/[dist or src]`

**Comment by humphd** [comment]
Who can work on this so we don't leave Thimble broken?

**Comment by gideonthomas** [comment]
fixed with https://github.com/sedge/thimble.webmaker.org/commit/16ce24c42b024e236d9f948c8c2a39a659baae03
