### ISSUE TITLE
CSS styles not updating preview

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#156]
With the last patch for multi-files landing in brackets-browser-livedev, when you add a `<link>` tag to a local css file, it should update the live preview immediately, but it does not. It seems like the blob url to the css file is being generated but the message is either not reaching the iframe or is not being used in the iframe because the link element cannot be seen in the live preview DOM.

@K-LV reports that this is not a problem on his twoServers branch so that might be a good point to start at.

**Comment by K-LV** [comment]
@gideonthomas hopefully this [PR] (https://github.com/humphd/brackets/pull/157) fixes this issue

**Comment by gideonthomas** [comment]
Fixed with 155a8620b371f05624b527925064c73f351661b7
