### ISSUE TITLE
CSS styles do not update the preview on using quick edit

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#159]
STR:
* Create an html file, save
* Create a css file, save
* Add a `<link>` tag in the html file to reference the css file
* Cmd+E on an element (which has styling rules in the CSS file) to open quick edit
* Begin editing a rule
* Witness an error in the console

**Comment by gideonthomas** [comment]
moving out of PPP.1 as issue is more complicated than expected.

**Comment by gideonthomas** [comment]
We have discovered a problem with this issue. 

Changes to a CSS file should be propagated to the preview as they are made. This means that a user should be able to click on an element, use quick edit to edit the style rules for that element and the changes should be reflected in the preview (if you save the changes to the css file, currently, it still does not update the preview unless you switch between documents).

Here is a potential solution:
* Change the way the rewriter works such that if it can't find the path to rewrite in the cache, it <strong>leaves it as it is</strong> and does not replace it with an HTTP404 url
* Listen for the `CSSStylesheetText` message in the `send` method of PostMessageTransport.js
* On receiving that message `msg`, call `CSSRewriter.rewrite` and send it `msg.params.css` and convert it to a blob url <strong>manually</strong> to generate a new blob url without looking up the cache. It will probably be a good idea to cache this somewhere as well so that we can revoke it when a `writeFile` is done or another similar message is received (requiring the generation of a new blob url)
* `reload` will change in the following way:
** It will accept two parameters - the url currently being used to link the CSS file (which can be accessed with `msg.params.url`) and the newly generated blob url
* The `reload` method should call the `launch` method as it's supposed to, however, it the `launch` method will change in the following way:
** It will accept the same two parameters that `reloadLinkedCSS` accepts
** It will call `serveLiveDoc` passing the above parameters
* In `serveLiveDoc`, the following will change:
** Before calling `HTMLRewriter.rewrite`, perform a regex on the content (which can be accessed with `liveDocument.getResponseData().body` to replace the url passed in with the new blob url)

Some of these steps might be able to be cut down, but I can't think of any right now.

cc @humphd

**Comment by humphd** [comment]
Doing a REGEX on XML is madness, don't do it.  This is why we use `DOMParser` in the rewriter.  I agree with not using 404s.  We should also be careful to have a strategy for cleaning up blob urls when they aren't needed any more.  Figuring out when it's safe to clean them up might be tricky.

**Comment by gideonthomas** [comment]
Fixed with humphd/brackets-browser-livedev@475fdad65f5f91b8425667159da3b11fe41722f2
