### ISSUE TITLE
Revoke stale URL Objects for a given file whenever we create a new one

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#162]
In `content.js` we have:

```js
        toURL: function(data, type) {
            var blob = new Blob([data], {type: type});
            return URL.createObjectURL(blob);
        }
```

We call this in a bunch of places to create HTML (when we launch a URL) and CSS (when we rewrite CSS) files reachable via the iframe browser.  Every call to `URL.createObjectURL()` probably needs to have a matching `URL.revokeObjectURL()` sometime in the future, so that we don' t leak URL objects.  The most common case for this is during a reload, where we are throwing away the old content/URL and making a new one.

We have code in `BlobUtils.remove()` that does this, but only when we cache the URL.  In the HTML case, we never do, so we never release it when we make a new one.  We need a strategy for cleaning this up.  One possibility would be to generalize the `BlobUtils` stuff a bit, and use it in cases where we aren't caching (e.g., HTML).  Another would be to have `toURL()` also take a filename, and we remember the old URL for a given filename, and revoke it when we update.

**Comment by humphd** [comment]
Just got this error testing things:

```uncaught exception: out of memory```

Yeah, this is bad :(  We need a fix.

**Comment by humphd** [comment]
Another thought occurs to me.  In `iframe-browser.js` we do this, when we alter the iframe's `src`:

```js
    function update(url) {
        if(url) {
            var iframe = getBrowserIframe();
            if(iframe) {
                iframe.src = url;
            }
        }
    }
```

Before we alter the `iframe.src`, we could do:

```js
...
// Release the existing blob URL object that was being previewed
URL.revokeObjectURL(iframe.src);
// Update to new URL object
iframe.src = url;
```

We might already have enough code paths to deal with CSS files and images.

**Comment by gideonthomas** [comment]
https://github.com/gideonthomas/nimble/commit/ce9d70be1bc6cc77100682cf5e2a9bbe57479736#commitcomment-10629979

**Comment by gideonthomas** [comment]
Another place we need to revoke the blob url is when we call `serveLiveDoc` in bbld where we generate a new blob url for the instrumented document. We should probably cache it and revoke it when we generate a new one

**Comment by humphd** [comment]
Talking with @K-LV about this on irc, I think the right strategy here is to move `Content.toURL()` into `BlobUtils` and rename it to `createURL(path, data, type)`.  The code would be something like:

```js
// Create a Blob URL Object, and manage its lifetime by caching.
// Subsequent calls to create a URL for this path will auto-revoke an existing URL.  
function createURL(path, data, type) {
  var blob = new Blob([data], {type: type});
  var url = URL.createObjectURL(blob);
  // NOTE: cache() will clean up existing URLs for this path.
  cache(path, url);
  return url;
}
```

Then all consumers of Blob URL Objects are free to use them without having to worry about lifetime management or leaks.
