### ISSUE TITLE
Fix right-click context-menu disappearing issue on Firefox

### ISSUE THREAD

**Issue by K-LV** [humphd/brackets#163]
Firefox seems to have a problem when right-clicking on the side panel. Right-clicking the empty, dark, area produces nothing on Firefox while on Chrome it displays a menu. A work-around, for Firefox, is to right-click an existing file, hold it, and left-click the desired option.

| Firefox                     |  Chrome |
|------------------------- | ------------------------- | 
| ![ff-right-click](https://cloud.githubusercontent.com/assets/9330361/7006771/b725e254-dc51-11e4-9727-67a034580afc.gif) | ![chrome-right-click](https://cloud.githubusercontent.com/assets/9330361/7006774/c18bc024-dc51-11e4-9826-d5dd1e1615d5.gif) |

**Comment by KeniMorri** [comment]
Found out whats going on, basically:

Firefox:
![screenshot 2015-04-08 13 23 13](https://cloud.githubusercontent.com/assets/1750230/7050948/b9d2126e-ddf2-11e4-8b3e-4a497302c584.png)

Chrome:
![screenshot 2015-04-08 13 23 28](https://cloud.githubusercontent.com/assets/1750230/7050951/bfd4c7c4-ddf2-11e4-8d0e-71bfb8deb92a.png)

Figuring out a fix now

**Comment by humphd** [comment]
Yeah, this is really interesting, and for sure it's 1/2 of the problem.  I wonder why the `project-files-container` doesn't stretch 100% of the way down?  Talking with folks on the brackets irc channel, one working theory is that Brackets is using old-style flex-box syntax, and Firefox is doing the wrong thing based on that.  I can't immediately see any `-webkit-*` type stuff being applied to this `div`.

**Comment by humphd** [comment]
The other problem here is that the `oncontextmenu` event handler seems to close the menu when the mouse button is released on Firefox but not Chrome.  So there's at least 2 bugs here, and it might be worth separating that out.

**Comment by humphd** [comment]
I wonder if `.box-flex()` needs a rewrite https://github.com/adobe/brackets/blob/ae17456a596965a1247b79ddb82c6e1518bc6e5e/src/styles/brackets_mixins.less#L55L59

**Comment by KeniMorri** [comment]
This issue has been split into 2, refered to in #180 and fixed in #182

**Comment by K-LV** [comment]
Update: using @KeniMorri's [fix 182] (https://github.com/humphd/brackets/pull/182), when you right-click on the lower portion of the sidebar the context-menu seems to function normally.
![ff-right-click](https://cloud.githubusercontent.com/assets/9330361/7140547/e4205d68-e299-11e4-8354-204b0e59dc45.gif)

**Comment by humphd** [comment]
This makes me wonder if there is some extra click handler of some kind attached to the `li` for the `index.html` file in the tree.

**Comment by KeniMorri** [comment]
Temp fix in PR https://github.com/humphd/brackets/pull/214

**Comment by K-LV** [comment]
We are landing this and filing upstream.
