### ISSUE TITLE
Update deployment to gzip files on S3

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#164]
S3 won't dynamically gzip files it serves, so they must be uploaded gzipped and [S3 needs to be informed about the change](http://docs.travis-ci.com/user/deployment/s3/#Setting-Content-Encoding-header).

**Comment by sedge** [comment]
This will require a rethinking of how we build and deploy our stuff to S3. Currently, travis-ci runs `grunt build-browser` and then deploys the built package to S3. We will need to modify either the build step (`gruntfile.js`) or the deploy logic (`.travis.yml`), possibly both.

**Comment by sedge** [comment]
This dun work

**Comment by humphd** [comment]
@jbuck, do you have tips for @sedge on what has to happen to make this work?  It's fairly high on my priority list to get this squared away so we can start pointing people at the work.

**Comment by sedge** [comment]
[This commit](https://github.com/humphd/brackets/commit/c34943cb467c695420af25505fa5a65c2abfe0b8) attempted to solve this problem, but ended up getting `304` response codes on the entire `/brackets` subdirectory. Most of the work is complete, but I won't have the time to attend to this for another few days.

If someone can spot what I did wrong so that I can *quickly* correct it then I could fix this today. I can't afford to devote much time to it though.

**Comment by jbuck** [comment]
When you run the compression script, [every single file becomes a 20 byte broken gzip file](https://github.com/gruntjs/grunt-contrib-compress/issues/132). Hooray!

**Comment by sedge** [comment]
@jbuck ++

**Comment by humphd** [comment]
```
12:43 <~jbuck> humph: looks like someone made a PR to fix this:
               https://github.com/gruntjs/grunt-contrib-compress/pull/149
```

**Comment by humphd** [comment]
@sedge if that PR works, let's just use the commit in package.json until they update npm.

**Comment by sedge** [comment]
Done!
