### ISSUE TITLE
Fix odd large text issue on load

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#173]
STR: Difficult
1. Load thimble
2. Change Text to Large
3. Reload Page
4. Error may be present, no guarantee

Example of error:
![screenshot 2015-04-07 13 33 19](https://cloud.githubusercontent.com/assets/1750230/7029296/b5fee3e2-dd2a-11e4-81a1-3227ea0c7687.png)
Note how close the Editor is to the gutter

Basically somehow, on load, the extension initializes the font change too early in brackets load and brackets cannot respond properly so the cursor is placed on the wrong line.

**Comment by K-LV** [comment]
We haven't seen this bug in a while. Re-file if it appears again.
