### ISSUE TITLE
Fix HtmlHinter errorToggle Disappearing issue

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#174]
When dealing with multiple files if we spawn the errorToggle button, then move onto a different file and spawn the errorToggle on that file the toggle disappears from the initial file.
![error](https://cloud.githubusercontent.com/assets/1750230/7029396/6673ac80-dd2b-11e4-9c64-081281bc4f87.gif)

**Comment by KeniMorri** [comment]
This issue most likely arises due to the extension only keeping track of 1 button at a time, I initially was looking into fixing this issue by using a Codemirror.on("Focus",) method but this might be a little bit resource intensive, due to focus relating to many things.

**Comment by AJDBenner** [comment]
Fixed with https://github.com/KeniMorri/HTMLHinter/pull/9
