### ISSUE TITLE
Live preview does not update blob url on save

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#175]
Noticed by @K-LV 

When we add a `<link>` tag to our html document and then go to make changes in the CSS file that is linked, it updates the preview fine. However, if we save that CSS document and then try to make changes, the live preview does not update as intended.

This seems to be because when we do a save, a new blob url representation is generated for the CSS file and that is the blob url used when messages are sent to the live preview regarding changes after save to the CSS file. However, the live preview currently has no way of knowing that the url of a related document viz. the CSS file has changed and been saved. So, it still uses the link url of the CSS file before the save and does not process incoming messages that contain the new url. We need a way to update the `<link>` tag's `href` on a file save, or trigger a reload on save or something like that.

**Comment by humphd** [comment]
This can get closed now, right?

**Comment by K-LV** [comment]
@humphd not yet. Waiting on review for https://github.com/humphd/brackets/pull/184.
