### ISSUE TITLE
Land brackets-browser-livedev in src/extensions/default

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#177]
We started out with `brackets-browser-livedev` as a submodule, partly because we wanted to keep `src/` is clean as possible for merging/submitting upstream work.  In that time the extension's code has become critical to working of Bramble, and I think it's time to consider landing the code directly in the repo and not using a submodule anymore.  Too often changes span both repos, and it's annoying and error prone to work that way.  We've got the proper isolation from Brackets code proper by doing so much in the extension at all.

**Comment by sedge** [comment]
@humphd This seems small, and a quick win. Shall I?
