### ISSUE TITLE
Update Brackets Sidebar Flex CSS

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#180]
Presently brackets is using an outdated version of flex, due to this the sidebar is not rendered properly within firefox

 Firefox                     |  Chrome            
------------------------- | ------------------------- 
 ![screenshot 2015-04-08](https://cloud.githubusercontent.com/assets/1750230/7050948/b9d2126e-ddf2-11e4-8b3e-4a497302c584.png) | ![screenshot 2015-04-08](https://cloud.githubusercontent.com/assets/1750230/7164890/8b331b04-e371-11e4-9117-932af1ed360a.png)  

To fix this I have updated the box css that were here:
https://github.com/adobe/brackets/blob/master/src/styles/brackets_mixins.less#L24-L69

with:
https://github.com/KeniMorri/brackets/blob/boxFlexUpdate/src/styles/brackets_mixins.less#L24-L68

One error that arose due to this change is that the extensions dialog looked broken:
![screenshot 2015-04-15 13 30 36](https://cloud.githubusercontent.com/assets/1750230/7165143/a4cc222a-e373-11e4-9059-cef96788dffa.png)

To alleviate this a few changes were needed, I changed the css to use .vbox, and removed the `<br/>` that was present in the html to fix this issue.

The proposed changes can be viewed in the comparison below:
https://github.com/adobe/brackets/compare/master...KeniMorri:boxFlexUpdate

**Comment by K-LV** [comment]
I can also confirm that, after adding this patch, the context menu is now visible when right-clicking in Firefox. However, it goes away unless right-click, hold, and hover over the menu.
![ff-right-click](https://cloud.githubusercontent.com/assets/9330361/7096918/5d0d3f00-df9f-11e4-96e6-dbfed72fea3e.gif)

**Comment by KeniMorri** [comment]
Although in general, the fixes I proposed in PR #182 does correct the issues in firefox, in relation to these lines:
https://github.com/humphd/brackets/blob/bramble/src/styles/brackets_mixins.less#L71-L76
I cannot seem to find a suitable replacement for them within the flex method. I can't find anything in relation to it breaking yet though.

**Comment by humphd** [comment]
What about elsewhere in the CSS/LESS?  Are there other places that need similar fixes?

**Comment by KeniMorri** [comment]
Updated main post
