### ISSUE TITLE
Allow ?ui=1 to override hiding of all desktop UI

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#185]
For the Thimble case, we really want to hide the menu bar, sidebar, toolbar, etc.  But it would be nice if we could override this and allow the full UI to still be displayed.  Let's alter the `brackets-browser-livedev` extension to check for a `ui=1` on the query string, and skip hiding UI elements when present.

**Comment by KeniMorri** [comment]
Alright, I'll look into implementing this
