### ISSUE TITLE
Add SVG back to language/languages.json

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#187]
I purged a bunch of languages that aren't needed from `src/language/languages.json` so that CodeMirror wouldn't load modes for them all.  However, I removed SVG, and we need it in for a patch I'm doing with QuickView.

Basically, adding these lines to our file:

https://github.com/adobe/brackets/blob/5daf5bea63b0ef602d3213427c1edb6a987150ba/src/language/languages.json#L101L106

**Comment by KeniMorri** [comment]
This is fixed in #188
