### ISSUE TITLE
Allow for a detached live preview window

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#189]
We would like to add a feature that allows the user to open the live preview in a new window (detached live preview). When the new window is opened the editor will hide the in-editor preview window (attached live preview), but still keep it up to date. When the detached live preview is closed the attached live preview will automatically open with the most up to date version of the document. This feature will involve many steps that will be created as separate issues.

Steps:
- Add a button to toggle between an attached and detached live preview state. Issue https://github.com/humphd/brackets/issues/190
- Keep track of the detached vs attached live preview state. Issue https://github.com/humphd/brackets/issues/191
- Add an event handler on the detached live preview to know if it's open or closed. Issue https://github.com/humphd/brackets/issues/192
- Hide the attached live preview window when the detached live preview is opened. Issue https://github.com/humphd/brackets/issues/193
- Open the attached live preview window when the detached live preview is closed. Issue https://github.com/humphd/brackets/issues/194
- Set the URL of the detached live preview window equal to the Blob URL of the attached live preview when the detached live preview is opened. Issue #196
- Manage both the attached and detached live previews at the same time. Issue #195

**Comment by K-LV** [comment]
Done in https://github.com/humphd/brackets-browser-livedev/commit/74a9fdabf3f99868fb38985caa082557e3ccecbd.
