### ISSUE TITLE
Swap out makedrive for filer

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#19]
We want `filer` as a filesystem, not `makedrive`.

**Comment by humphd** [comment]
This should include a few steps for our MVP:
* remove the MakeDrive submodule
* add the Filer submodule in its place
* rename `src/filesystem/impls/makedrive` to `src/filesystem/impls/filer` and all files underneath that from `MakeDrive*` to `Filer*`
* Expose `Filer` on `appshell` like we used to do with `MakeDrive` https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/makedrive/MakeDriveFileSystem.js#L24
* Add a new method to the Filer object, `fs()` which does what `MakeDrive.fs()` does (i.e., create and/or return a single filesystem instance)
* Switch to the Filer Memory provider for a backend vs. using IndexedDB or WebSQL (we'll use those later).
* Update our extensions that use the filesystem via `appshell.MakeDrive.fs()` to use `appshell.Filer.fs()`
* Change `src/main.js` to load the Filer filesystem impl vs. MakeDrive https://github.com/humphd/brackets/blob/bramble/src/main.js#L38

I think that's everything.
