### ISSUE TITLE
Add an event handler on the detached live preview

### ISSUE THREAD

**Issue by AJDBenner** [humphd/brackets#192]
This is part of #189. We need to have an event handler as part of the detached live preview window to know if the detached live preview is open or closed.

**Comment by humphd** [comment]
If this proves to be hard to do, just using the `detachedWindow` instance directly, another solution would be to use the remote transport script to add a `unload` event handler that sends a messages over the transport indicating that the window is closing.  We could then deal with this on the editor side and do whatever clean up is necessary.

**Comment by K-LV** [comment]
Done in https://github.com/humphd/brackets-browser-livedev/commit/74a9fdabf3f99868fb38985caa082557e3ccecbd
