### ISSUE TITLE
Startup project should allow arbitrary content, and multiple files

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#198]
A request I've gotten from a few people is to allow starting the app with arbitrary content, which might be a single HTML file, or a bunch of HTML, CSS, JS files.  You can already do this with sites like jsfiddle, where I can author some content, save it, get a URL and when you open it, you get back the same content.  I want to be able to do this with an entire web project that has many files.  In essence, you're opening not only an editor, but also a project via a single URL.

Solving this completely likely requires server-side code, but there will be aspects of this that are Brackets facing.  Specifically, we currently assume that we'll get content for a single HML file from the parent window via `postMessage`, and then save this to `/index.html`.  It would be nice to figure out a way to allow more complex hierarchies to be used.  Maybe we should use something like `tar` in JS to allow passing a single stream which we can then expand into the filesystem.

@modeswitch, did you implement tar/untar at some point for filer?  Can you point me at what you did, if so?

**Comment by humphd** [comment]
Talked to @modeswitch on irc, and his old tar code is in this commit: https://github.com/filerjs/filer/commit/ad3aa5eac8f7730009ad7c1fe84cccfb133a7c7c

**Comment by humphd** [comment]
It would be interesting to think about publishing as "tar the filesystem, and send that to the server" and edit/open as "xhr a tar file from the server and expand to the filesystem."

**Comment by modeswitch** [comment]
Yeah, that's a wonderful idea.

I had planned to add support for something like this as an option during formatting anyway, and this would be a more general version of that.

**Comment by sedge** [comment]
@humphd Have we already solved this? If not, we'll need to. I suspect your patch to switch makedrive providers might do the trick.

**Comment by humphd** [comment]
We're solving this in Thimble, closing here.

**Comment by humphd** [comment]
FYI, I'm doing this in Bramble and Thimble (starting with Bramble here https://github.com/humphd/brackets/pull/416).  I ended up using https://github.com/humphd/bitjs, which I forked from Google Code.  It's really great, because it does it on a worker.
