### ISSUE TITLE
See if we can reduce reloads for non-script changes to the DOM

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#202]
In #105 we landed patches by @busykai to allow inline script changes to trigger a reload, and thus let the preview better reflect the state of the editor.  They work great.  The patch also fixed the issue of copy-pasting/replacing the entire `html` element, which is a common case for us.

One effect of these changes is that we reload often, and unnecessarily in cases where we are simply editing something in `body`.  I'd love to see if we can further reduce the frequency of reloads relative to edits in the editor, without losing script updates or `html` replacement.  Perhaps we have this as good as we can get it; but I wonder if we can filter out top-level changes that are really going to blow away the whole DOM (and require a reload) vs. things that could actually just be diffs that we apply to the current preview.

@gideonthomas, maybe you can poke at this?  I'd look at the changes we did in #105 and how they might be tweaked.

**Comment by humphd** [comment]
I realize that I'd merged an older branch of `kai/fix-5656-live-dev` which didn't have https://github.com/adobe/brackets/commit/f22dc1c754254c461cca831e9f985bf282d459b2.  I've corrected this now, and our `bramble` branch has it.

It makes things a bit better, in that the `shouldReload` case is now not triggered if I just edit text content within an existing node.  But if I try to add a `p` element to the `body`, it still wants to rewrite the whole HTML.

**Comment by humphd** [comment]
Tracing through this code, I'm almost wondering if we shouldn't do a hybrid approach, and not do the `shouldReload` case for `html` and add this back https://github.com/adobe/brackets/pull/10653/files, leaving `shouldReload` for `script`.  Needs some testing.  It might not be perfect, but I think it might be less noisy with reloads for the common case (e.g., altering a small bit of the DOM vs. whole thing).

**Comment by busykai** [comment]
@humphd, `html` was added in `shouldReload` to address adobe/brackets#10634: editing html root nodes (`html`, `body`, `head`) cannot be done in a reasonable fashion via injected scripts (this is the reason why adobe/brackets#10653 was not a reliable solution), so any DOM edited subtree which has `html` as the root would cause reload.

**Comment by humphd** [comment]
Alright, given that let's keep things as they are.  Thanks.
