### ISSUE TITLE
Detachable preview status bar icon should be a toggle

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#205]
Our current status bar button for the detachable live preview is one-way, namely, it assumes that you want to detach the preview and open it in an external window.  However, it would be nice if it *also* worked the other way too, and when you click it to detach the preview the following happened:
* icon changes to the one I specified here https://github.com/AJDBenner/brackets-browser-livedev/pull/3#issuecomment-93536616
* tooltip changes to reflect that clicking will attach preview window to editor
* click handler is smart enough to know that it should close the external window and re-show the inline preview (this might already be true).

**Comment by KeniMorri** [comment]
I've implemented a toggle in my experimental branch here:
https://github.com/AJDBenner/brackets-browser-livedev/pull/7

another change is a switch to svg's because they'll scale nicer

**Comment by K-LV** [comment]
Done in https://github.com/humphd/brackets-browser-livedev/commit/74a9fdabf3f99868fb38985caa082557e3ccecbd.
