### ISSUE TITLE
MVP of a Mobile Preview mode

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#206]
Currently the preview we do is showing what things look like on desktop.  It would be neat if we could switch to a preview that looks like what you'd get running on a mobile phone.  Let's add a simple version of this by doing the following:
* Add another status bar toggle button with two icons from http://modernuiicons.com/: appbar-iphone and appbar-monitor.  By default it would show the phone icon, meaning you can switch to mobile mode.
* Clicking the button flips between mobile and desktop modes
* In mobile mode, we'd do something like http://jsfiddle.net/e27n8hq7/6/, with the phone centered horizontally/vertically in the preview area, and the actual content rendered in the phone's iframe

**Comment by AJDBenner** [comment]
Fixed with https://github.com/humphd/brackets-browser-livedev/pull/63
