### ISSUE TITLE
Change how related stylesheets and scripts are indexed in Bramble

### ISSUE THREAD

**Issue by K-LV** [humphd/brackets#212]
Brackets keeps a list of related stylesheets and scripts pertaining to a particular live HTML document. These scripts and stylesheets are indexed by URLs as seen here.

![screen shot 2015-04-18 at 11 05 46 pm](https://cloud.githubusercontent.com/assets/9330361/7217980/8744a5d4-e61f-11e4-9022-684156e84697.png)

To get this list, of related documents, Brackets calls the [isRelated] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/documents/LiveHTMLDocument.js#L309) function. From there, the [resolveURL] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/LiveDevMultiBrowser.js#L244) function is called. This function takes a path and returns the URL of that document, if it exists.

The problem lies in that, in our Bramble code, the related stylesheets and scripts are indexed by path rather than URL. 

![screen shot 2015-04-18 at 11 20 55 pm](https://cloud.githubusercontent.com/assets/9330361/7218016/9f080e20-e621-11e4-8074-3ffe4e717c17.png)

In our fix for [issue#184] (https://github.com/humphd/brackets/pull/184) we rely on the isRelated function to work as intended. This means that we must change the way resolveURL works. A working approach is to have the resolveURL function return the path, unchanged. It's a safe fix for now as the function is not called anywhere else. This fixes our problem but could cause problems down the line if Brackets ever updates their code and uses the resolveURL function again. 

I suspect that the problem may lie in our brackets-browser-livedev extension. The  PostMessageTransport file contains a function called [resolveLinks] (https://github.com/humphd/brackets-browser-livedev/blob/master/lib/PostMessageTransport.js#L40). This function intercepts the incoming messages and replaces the URLS of stylesheets and scripts with their paths. It's possible that this occurs before the stylesheets/scripts are added to the related documents list.

**Comment by sedge** [comment]
@humphd Is this a problem? I'm confused about this issue.

**Comment by humphd** [comment]
This could evolve to become a bug, but isn't yet.  I think we should fix it when it is.  Closing for now.
