### ISSUE TITLE
Allow overflow scrolling when in mobile preview mode

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#219]
![screen shot 2015-04-20 at 2 15 10 pm](https://cloud.githubusercontent.com/assets/427398/7237227/2564dcea-e768-11e4-9051-f68ccb186d2a.png)

In the mobile preview mode, we don't have the proper overflow scrolling for cases where the window isn't large enough to display the entire contents.  This is probably also a problem with desktop mode, but isn't going to get hit as often.

**Comment by gideonthomas** [comment]
how would we fix this? make the size of the phone smaller? Seems like it won't look too good

**Comment by gideonthomas** [comment]
Oh wait, nvm I understand now

**Comment by AJDBenner** [comment]
Fixed with https://github.com/humphd/brackets-browser-livedev/pull/64
