### ISSUE TITLE
[Firefox] "SecurityError: the operation is insecure." accessing sheet.cssRules

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#220]
Firefox is picky about accessing stylesheets from other domains:

```js
    /**
     * Retrieves related documents (external CSS and JS files)
     * 
     * @return {{scripts: object, stylesheets: object}} Related scripts and stylesheets
     */
    function related() {

        var rel = {
            scripts: {},
            stylesheets: {}
        };
        var i;
        // iterate on document scripts (HTMLCollection doesn't provide forEach iterator).
        for (i = 0; i < _document.scripts.length; i++) {
            // add only external scripts
            if (_document.scripts[i].src) {
                rel.scripts[_document.scripts[i].src] = true;
            }
        }
          
        var s, j;
        //traverse @import rules
        var traverseRules = function _traverseRules(sheet, base) {
            var i;
            if (sheet.href && sheet.cssRules) { // <-------- here
```

See http://stackoverflow.com/questions/21642277/security-error-the-operation-is-insecure-in-firefox-document-stylesheets for an idea on fixing.

**Comment by humphd** [comment]
The code is from [https://github.com/adobe/brackets/blob/b8f92c1b36c2a15396e36b732d7f3fe52e8f4a8d/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/DocumentObserver.js#L60](LiveDevelopment/MultiBrowserImpl/protocol/remote/DocumentObserver.js).  

cc @busykai

**Comment by busykai** [comment]
@humphd is it nightly or any FF will do? I'll re-file this with `adobe/brackets` with your permission.

**Comment by humphd** [comment]
I've confirmed this is reproducible upstream, and filed here https://github.com/adobe/brackets/issues/10965

**Comment by humphd** [comment]
This has landed upstream, we need to rebase.  I'm waiting on @gideonthomas to land some other fixes first, let's do this early next week.

**Comment by humphd** [comment]
@gideonthomas can I do a rebase onto Adobe's master yet?  Then I can close this.

**Comment by humphd** [comment]
This has landed in our fork now, closing.
