### ISSUE TITLE
Fix LivePreview being unable to jump between local files

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#221]
Presently we are unable to jump between local html files within thimble inside the live preview

Thimble
![thimble](https://cloud.githubusercontent.com/assets/1750230/7255295/4d083662-e816-11e4-8408-a12d4db827d3.gif)
Brackets
![thimble2](https://cloud.githubusercontent.com/assets/1750230/7255298/4deab7b2-e816-11e4-9a15-d7c266a966f1.gif)

**Comment by humphd** [comment]
@gideonthomas can you look at this one?

**Comment by humphd** [comment]
https://github.com/humphd/brackets/pull/227 is fixing this.
