### ISSUE TITLE
Figure out why Brackets Status Bar disappears using mobile preview

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#228]
If you click outside of the mobile preview, the brackets status bar disappears, even pressing within the preview does not make the status bar reappear. The status bar will only reappear if you press back into brackets
![screenshot 2015-04-21 16 02 59](https://cloud.githubusercontent.com/assets/1750230/7261549/a6985b9c-e840-11e4-9ba5-91fb3fd4d022.png)

vs.

![screenshot 2015-04-21 16 04 39](https://cloud.githubusercontent.com/assets/1750230/7261555/c0ea08f6-e840-11e4-830a-b61c8f4991b4.png)

**Comment by humphd** [comment]
![screen shot 2015-04-21 at 4 23 49 pm](https://cloud.githubusercontent.com/assets/427398/7261844/dc476074-e842-11e4-8ef0-76b6f4630f7c.png)

I notice that in the DOM, the children of the `status-bar` div are all getting `display:none` added for some reason.

**Comment by humphd** [comment]
Sorry, closed by accident, re-opened.

**Comment by KeniMorri** [comment]
As I suspected the reasoning why we're losing the Status bar is because we're losing focus from an editor.

STR: In vanilla brackets
1. Open Brackets (Assuming you're set to No Split curently)
2. Click View
3. Select Vertical Split
4. Click within the 2nd panel
5. Observe that the status bar disappears

Basically from what we can gleam from this is that the area surrounding the iframe in our mobile preview has the same properties as the 2nd panel. If I had to guess its because we're not giving brackets anything to focus on specifically thus the status bar shows nothing because we're not focusing on an editor(which would display various status's of that current editor instance)
![screenshot 2015-04-22 13 33 25](https://cloud.githubusercontent.com/assets/1750230/7280962/78707628-e8f4-11e4-8bb6-dacba755c098.png)

**Comment by K-LV** [comment]
So, if we made the iframe live inside a new preview window it might solve the problem? If so, this might also fix https://github.com/humphd/brackets/issues/233#issue-70142770.

**Comment by humphd** [comment]
Can we somehow prevent the preview frame holder from getting focus?

**Comment by humphd** [comment]
Another option is to have the `click` event just call `focus()` on the editor, and force it back there.
