### ISSUE TITLE
all dialogs throw error

### ISSUE THREAD

**Issue by awebdeveloper** [humphd/brackets#231]
Throws error on opening of any dialogs 

Uncaught Error 

 function showOpenDialog(allowMultipleSelection, chooseDirectories, title, initialPath, fileTypes, callback) {
        // FIXME
        throw new Error();
    }

**Comment by humphd** [comment]
Which branch are you using?  If you're on the `bramble` branch, this should work.

**Comment by humphd** [comment]
I'm going to close this, since we do this in `bramble` here: https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/filer/FilerFileSystem.js#L21-L27.  Feel free to file more bugs if you get stuck.
