### ISSUE TITLE
[IE10] SCRIPT5: Access is denied. when detaching preview

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#233]
When you try to detach the preview into its own window, IE throws a security exception:

![screen shot 2015-04-22 at 10 26 04 am](https://cloud.githubusercontent.com/assets/427398/7276770/1f1d061e-e8da-11e4-83a5-fa31cd36d3a2.png)

Doing a bit of reading about this, I *think* that it doesn't like the way we're loading the preview iframe, and that it thinks it's another domain.  Some sites I've read have said that injecting a simple HTML page (i.e., HTML string vs. URL), which hosts the iframe, might fix it.  This could also be used by us to enable the mobile view in the detached preview.

**Comment by humphd** [comment]
The mobile and detachable preview need to get refactored and use the new `lib/compatibility.js` stuff I landed to make the preview work in IE.  Basically, we have to `document.write()` the raw HTML into the window/iframe vs. using a blob URL, since IE doesn't support blob URLs with type `text/html`.

**Comment by gideonthomas** [comment]
`PostMessage` is not well supported in IE so we are gonna disable the detachable preview button for IE10 and below and have it work in IE11 partially (only when a reload is triggered by the editor)
