### ISSUE TITLE
Automatic debugger support

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#244]
One neat trick you can do is to open the dev tools in your browser, add the `debugger` keyword to a line, and get dropped directly into the running script at that line so you can debug:

![screen shot 2015-04-28 at 11 14 39 am](https://cloud.githubusercontent.com/assets/427398/7372991/ee3ce9de-ed97-11e4-9358-d023620cf097.png)

It would be interesting to experiment with adding a way to click beside a line in the editor, and if it's JS, automatically add the `debugger` keyword so you get this for free.

**Comment by gideonthomas** [comment]
I think this would be great to do as an extension

**Comment by sedge** [comment]
+1

**Comment by humphd** [comment]
I don't think we should do this.
