### ISSUE TITLE
Make localization configurable via URL param

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#245]
Brackets uses [RequireJS's i18n localization](https://github.com/adobe/brackets/wiki/Localization).  The choice about which locale to use is done in `src/main.js` [here](https://github.com/humphd/brackets/blob/bramble/src/main.js#L50-L60).  Given that Bramble is always going to need to be loaded into an iframe, and given how early the locale is set (i.e., we can't do this via `postMessage` to our extensions, since they aren't loaded yet), we could look for something like `?locale=fr` on `window.location.search`.  This can then get set via the hosting app (e.g., Thimble), which can supply a locale value or just let things default to `en`.

**Comment by JordanTheriault** [comment]
Merge pending in #283

**Comment by gideonthomas** [comment]
Fixed with 022ec9d98732fa6247d6b280e235ff9b586237c4
