### ISSUE TITLE
Create ImageUrlCodeHinter provider based on UrlCodeHinter

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#246]
We want a code hinter that activates when:

1. `<img src=` is typed
2. In a CSS file, `background : url(` is typed
3. In an HTML file, in a style tag, `background : url(` is typed
3. In an HTML file, in a style attribute, `background : url(` is typed

and provides a list of files in the (for MVP) root of the project.

**Comment by sedge** [comment]
Once this is complete, we want to add an option for "Take a picture", allowing a webcam snapshot or a stock image if webcam WebRTC stuff isn't supported.

**Comment by humphd** [comment]
`ImageUrlCodeHinter`?

**Comment by humphd** [comment]
Let's begin by basing this on `UrlCodeHints`.

**Comment by sedge** [comment]
The current state of this feature is stored in https://github.com/humphd/brackets/tree/selfie . 

Closing.
