### ISSUE TITLE
Move Toolbar to left-hand side, update buttons

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#248]
I think we should consider borrowing Visual Studio Code's left-hand toolbar style:

![screen shot 2015-05-05 at 5 15 58 pm](https://cloud.githubusercontent.com/assets/427398/7483144/9c4b7420-f34a-11e4-9155-cee5957204a6.png)

My thinking is that we put the editor on the left, and the preview on the right.  Therefore the tooling should go with the editor pane.

I'd also like to change the button layout to include:
* Show/hide Filesystem Tree View
* Mobile preview mode (move this out of the status bar, into toolbar)
* Detach/Re-attach preview mode (move this out of status bar, into toolbar)
* "Save" which could save any dirty files that are open
* Remove "Extension" button
* Maybe remove Live Dev lightning bolt (I think we always want this on?)
* Maybe add Quick Edit?

I think we can do this change and not actually show it yet (i.e., keep it hidden while we do multi-file support)

**Comment by sedge** [comment]
In general, +1.

It would be nice to get some designer feedback on this. My instinct is that the toolbar will quickly become cluttered and disorganized if we try and stuff all of that in without thinking it through.

**Comment by humphd** [comment]
Agreed.  I'll get some UX help with this before we move forward.

**Comment by humphd** [comment]
I'm going to close this, now that we have @flukeout helping doing UX design.  We'll address this in other ways.
