### ISSUE TITLE
SelfieTaker: Some CSS properties don't work

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#257]
This is more of a usability issue:
the background-image property in a CSS file should show code hints for the url function but it does not show Take a selfie until you type in the first quote (which should not be the case since it does not need quotes).

![background-image bug](https://cloud.githubusercontent.com/assets/5816130/7544852/00bd650c-f59f-11e4-9512-bb53477e4718.gif)

**Comment by humphd** [comment]
I noticed this too.  It's probably worth filing upstream for the UrlCodeHints extension, too.

**Comment by sedge** [comment]
Has this been confirmed in vanilla brackets? I suspect it's in our logic somewhere.

**Comment by sedge** [comment]
I've confirmed that UrlCodeHints doesn't have this problem:

![screen shot 2015-05-11 at 9 59 16 am](https://cloud.githubusercontent.com/assets/1616860/7566389/7d16c018-f7c4-11e4-912f-bb9e830f3af4.png)

**Comment by humphd** [comment]
NOTE: you did `background` vs. `background-image`.  Can you see if that matters?

**Comment by sedge** [comment]
Good catch - `background-image` with `url(` is broken upstream too.

**Comment by gideonthomas** [comment]
@sedge can you file this upstream?

**Comment by gideonthomas** [comment]
Filed upstream https://github.com/adobe/brackets/issues/11088

**Comment by gideonthomas** [comment]
https://github.com/adobe/brackets/pull/11139

**Comment by humphd** [comment]
This landed upstream.  I'm going to rebase today at some point in order to get this fix.
