### ISSUE TITLE
Renaming files with same name gives "Unknown Error" warning

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#259]
When renaming files, the user is given an unknown warning when they attempt to name a file the same as another one in the directory. 

This should give an error which informs the user there is already a file with the same name.

![screenshot 2015-05-11 09 49 38](https://cloud.githubusercontent.com/assets/5931078/7566178/5e67ee7c-f7c3-11e4-8912-817c8a3fea18.png)

**Comment by humphd** [comment]
I tried this in desktop Brackets, and it does this:

![screen shot 2015-05-12 at 12 58 36 pm](https://cloud.githubusercontent.com/assets/427398/7593248/b2f43e3a-f8a6-11e4-9827-5e8d2258e36e.png)

The error message comes from our filesystem impl, where we map Filer errors to Brackets errors.  The fix will be in https://github.com/humphd/brackets/blob/bramble/src/filesystem/impls/filer/FilerFileSystem.js#L28-L59 to catch the error you get when the other file exists, probably `EEXIST` but I'd have to confirm.
