### ISSUE TITLE
Enhancement: User modes

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#266]
User modes would improve tutorials and user experience by fine-tuning the coding environment. These modes are for CSS editing, HTML-only, advanced, basic and more. They will be enable or disable extensions and features depending on the mode selected.

**Comment by humphd** [comment]
From a backend point of view #265 would make this pretty easy.

**Comment by humphd** [comment]
This also ties into #243, where we could do an API for this.

This bug probably belongs in Thimble, where we'd define a series of URLs for use with the editor iframe.  These URLs would disable/enable various extensions using what we landed in #265.
