### ISSUE TITLE
Selfie: UI jumping during video stream load

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#271]
UI is doing a re-size once video loads which is visually unappealing.

Options to fix:
1. Wait for the stream to load, then present modal
2. Set background size since we know what it will be, and set the background colour to black.

**Comment by sedge** [comment]
@humphd Here's how it looks now on my marginally less powerful machine:

![resizefixed](https://cloud.githubusercontent.com/assets/1616860/7596198/fd11fe0e-f8b9-11e4-96ea-fe51945ce68d.gif)

**Comment by JordanTheriault** [comment]
^ from [this branch](https://github.com/JordanTheriault/brackets/tree/issue264)
