### ISSUE TITLE
SelfieTaker: Cat image is sized incorrectly on polaroid

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#274]

**Comment by sedge** [comment]
Cuz: 
![screen shot 2015-05-12 at 3 37 43 pm](https://cloud.githubusercontent.com/assets/1616860/7596604/e19b6a9a-f8bc-11e4-8aa4-1bd35834d4c3.png)

**Comment by JordanTheriault** [comment]
fixed in [#275](https://github.com/humphd/brackets/pull/275)
