### ISSUE TITLE
Right-clicking randomly deletes text from the editor window

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#290]
Right clicking on text once highlighted deletes the text from the editor.

![zzh1gsi](https://cloud.githubusercontent.com/assets/5931078/7708649/163fba90-fe25-11e4-9019-90da183b05b4.gif)

**Comment by humphd** [comment]
I bisected, and this was caused by https://github.com/adobe/brackets/commit/a0daa3a79d679201c5017529d5f0e5aa3a3232ea upstream.

**Comment by sedge** [comment]
Filed upstream @ https://github.com/adobe/brackets/issues/11142

**Comment by sedge** [comment]
This has been reported as fixed, and brackets has been rebased.
