### ISSUE TITLE
Hook up brackets to use thimble's filesystem

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#305]

**Comment by humphd** [comment]
We discussed this a bit today and there are some things to ponder, for example, how deep do we want your file tree to be?  Do we show you the current project, or do all your previous projects also show?

I think the simplest way to do this is to have each editing session use `/` and have only the files for the current project be in the file tree.  If you want to work on another project, you open another editor.  In other words, the editor is 1:1 with a user's project vs. a user (and all his/her projects).  This implies that there is some kind of other UI in Thimble or something to allow you to find your old projects and re-open them.

**Comment by humphd** [comment]
Our solution is going to be that your filesystem is a project, that is, your root dir `/` is the top of your current project.  You can't see other projects from this filesystem.

**Comment by sedge** [comment]
At this point we've decided that thimble will be responsible for the filesystem proper, and some portion of it will be exposed to brackets depending on which project is open.

**Comment by humphd** [comment]
I've got a proxied filesystem working with MessageChannel in https://github.com/humphd/brackets/tree/standalone.  I need a few days of work on it to make it perform better, and to fix some loading bugs in Firefox.

**Comment by humphd** [comment]
We need to remove all the `process-tick` events between filer windows: https://github.com/filerjs/filer/issues/352.

**Comment by sedge** [comment]
As a followup, we have to tolerate the `process-tick`. See filerjs/filer#352 for updates.

**Comment by humphd** [comment]
This is all done now.

**Comment by sedge** [comment]
:tada:
