### ISSUE TITLE
Support importing/exporting .zip archives

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#306]
* Maybe dropbox integration?
 * Just the design
* As zipped files (import/export)
* Drag and drop?
* URL to files?

**Comment by humphd** [comment]
If we decide to allow DnD into the filetree or editor window somehow, we should consider whether to do this upstream or just in our fork--there are bugs on this and/or Trello cards for this feature in Brackets.

**Comment by humphd** [comment]
The "unzip into filesystem" stuff is something I wrote here, and we could rework into an extension we load if you need that feature (i.e., don't always load it, since the zip/unzip code isn't small):

https://github.com/humphd/nohost/blob/master/src/webserver.js#L29-L84

**Comment by humphd** [comment]
From discussions today, our plan is:
* Allow a user to `Import` a file or files.  This could be done with a button and dialog box, drag-and-drop, both
* If it's a regular file or files, we add it to the current filesystem
* If it's a zip file, we ask whether they want to expand it into the current filesystem OR use it as the basis for a new project
* We also allow a user to `Open` a project by URL (i.e., an existing published URL for a project) or name (username/project-name or something).  This could be their own, or someone else's, which is similar to the concept of a remix.

**Comment by humphd** [comment]
I've done the file-import via dnd, so I've morphed this into the zip import/export bits.

**Comment by humphd** [comment]
I'm going to do the zip export in #347, and close this now that I've landed the zip import stuff.
