### ISSUE TITLE
UI/UX Markdown Quick Start doc

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#307]
Allow creating a markdown file to describe instructions for creating web apps which maybe are rendered instead of the default `index.html` file.

**Comment by humphd** [comment]
Depends on #238 for backend bits.

My idea here is that we introduce conventions around having a markdown file in a multi-file project, and if present, render it along with the preview.  For example, imagine if `README.md`, `INSTRUCTIONS.md`, `LEARN.md`, etc were names that triggered the editor to do something different on start-up.  Normally we look for an `index.html` file to render in the preview.  However, we could also choose to show a markdown file if present, and/or provide a switchable preview view (maybe tabs?) that let you jump between the preview HTML and the markdown.

This would let us easily support having instructions/tutorials written in markdown inside a project.

**Comment by humphd** [comment]
This is part of what we're discussing for tutorials in MVP, cc @flukeout.

**Comment by humphd** [comment]
I've basically got this working in #392 for a `tutorial.html` file.  It's unclear whether or not we want to support Markdown or not, based on conversations with Hannah and Luke.  I might rip the MD stuff out.

**Comment by humphd** [comment]
This is landed.
