### ISSUE TITLE
Design generic in-progress dialog

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#312]
There are a bunch of async operations we need to do in Bramble that need to somehow indicate to the user that they need to wait.  This includes things like processing files, downloading/uploading files, or any other long running operation we have to do on the main thread.

I'd like to see us come up with a generic, reusable dialog that we can use in a bunch of situations to communicate this information.  Ideally it has some way to show a message (what's happening, what you're waiting on), and some kind of progress indicator or throbber.  Consider things already used to do this:

 ![option1](https://thedevelopersinfo.files.wordpress.com/2009/10/with_title2.jpg)
![option2](http://www.ookii.org/Content/software/images/progressdialog.png)
![option3](http://www.emmbimobile.com/blog/wp-content/uploads/2013/07/device-2013-07-24-215631.png)
![option4](http://www.scodigo.com/images/sp2/barber_pole.jpg)

We won't always have a clear idea how long a process will take, so a throbber vs. a progress meter might be good.

**Comment by JordanTheriault** [comment]
A whimsical animation may be best for this, such as the one created for the [Mozilla Dev Derby](http://codepen.io/Sonick/pen/vijJl) or the ghost animation in Snapchat as it's entertaining, but does not indicate a specific time.

**Comment by sedge** [comment]
I'm not sure this is relevant for this milestone. Removing

**Comment by humphd** [comment]
We haven't got much traction on this, so I'm going to close and we can refile if we need it later.
