### ISSUE TITLE
404s on staging

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#314]
I'm seeing these 3 404s on staging right now, none of which should happen afaict:

```
GET https://mozillathimblelivepreview.net/bramble/dist/thirdparty/filer-dialogs/style/style.css
GET https://mozillathimblelivepreview.net/bramble/dist/thirdparty/filer-dialogs/bower_components/font-awesome/css/font-awesome.min.css
GET https://mozillathimblelivepreview.net/bramble/dist/styles/bramble_overrides.css
```

**Comment by humphd** [comment]
@gideonthomas, @JordanTheriault can you two look, these are things from your recent bugs.

**Comment by sedge** [comment]
Filer-dialogs was never corrected, but there's a [WIP patch](https://github.com/humphd/brackets/pull/151) I wrote that got lost. It needs lazy loading of font-awesome once to be shared between any extensions that need. it.

**Comment by sedge** [comment]
`bramble_overrides.css` is the firefox fix, but hasn't been forced to be included in the build step which is why it can't find it on staging.

**Comment by sedge** [comment]
In fact, @JordanTheriault has a patch for the bramble_overrides stuff here: https://github.com/humphd/brackets/pull/310/files

**Comment by humphd** [comment]
The filer-dialogs stuff got changed yesterday, see https://github.com/humphd/brackets/pull/309.  @gideonthomas, why is it 404ing?

**Comment by gideonthomas** [comment]
looking into it
