### ISSUE TITLE
Reduce size of dist/

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#37]
Right now the Brackets code in `dist/` (once we build it with `grunt build`) weighs in at 12.1M on the wire.  This includes the HTML, minified JS and CSS, images, fonts, etc.

Looking at the list of things we load, there are some obvious places to start:
* Get rid of any extensions we don't need from https://github.com/humphd/brackets/blob/bramble/src/utils/ExtensionLoader.js#L398-L420
* Don't build/ship source maps for JS and CSS (it's ~5M)
* Get rid of all the CodeMirror2 modes for languages we don't care about (they are all in `dist/thirdparty/CodeMirror2/mode/`).  We probably only care about html, css, js, markdown, json, and xml to start with.
* Investigate if there are other ways we can do our own custom build of CodeMirror2 to save space (i.e., those mode files aren't minified)
* Figure out which parts of Brackets itself we can dump.  For example, we don't need things like application auto-updating, installing new extensions, etc.

**Comment by humphd** [comment]
It looks like we can probably reduce the CodeMirror2 modes by altering the following file:

https://github.com/adobe/CodeMirror2/blob/master/mode/meta.js

Notice that Brackets uses a submodule pointing to an Adobe fork of CodeMirror2.  We might need to do our own fork that alters the `mode/meta.js` file and cuts it down.

**Comment by humphd** [comment]
Actually, this might be useful to explore too - http://codemirror.net/doc/compress.html

**Comment by peterflynn** [comment]
@humphd Cool, just ran across your fork here -- I'm excited to see you guys making progress with the Nimble stuff!

For keeping the dist size low, I'm guessing you could get rid of the `node` folders under `extensibility` and `filesystem` (and their `node_modules` subtrees, which might be big-ish).  If you do that by modifying the Grunt script, feel free to send it back as a PR into the `pflynn/in-browser-file-system` branch too :-)

**Comment by humphd** [comment]
Started on this, making some progress - https://github.com/humphd/brackets/pull/53
