### ISSUE TITLE
Update travis for new infra

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#383]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade is what I see when I run our builds on travis.  We should add `sudo: false` unless someone sees a reason not to?

**Comment by sedge** [comment]
I could have sworn I'd already done this! Clearly not.

r? https://github.com/humphd/brackets/pull/384
