### ISSUE TITLE
API should expose a rename method

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#385]
I need a way to tell bramble to rename the project folder when the project is renamed on the front-end. For this, I need something like `bramble.renameMountDir(newMountDirName);`
@humphd any thoughts?

**Comment by humphd** [comment]
I'm going to fix this by allowing you to call `Bramble.mount()` multiple times, and the second, third, nth time will be treated as update calls.  In other words, you'd do the rename yourself in the `fs`, and then tell Bramble about it via a `mount()` call with the new path.  I'll have a PR up this morning.

**Comment by gideonthomas** [comment]
+1 to this solution

**Comment by gideonthomas** [comment]
Reopening because this is now needed for https://github.com/mozilla/thimble.webmaker.org/issues/756

**Comment by gideonthomas** [comment]
Changing our approach in thimble to circumvent this issue
