### ISSUE TITLE
working on several files, closing FF, reopening, rebrambling: files got reset

### ISSUE THREAD

**Issue by Pomax** [humphd/brackets#414]
I was working on a lot of files in bramble, making a few new files but keeping index.html and style.css - after closing FF, then reopening and reloading bramble those two files have been reset to their original form, while the new files I made are still the ones I had when I closed FF.

(I saved my work manually, so nothing got lost, but this seems a fairly critical bug)

**Comment by humphd** [comment]
You're using `hosted.html` I assume?  It's not really meant for real-world uses, just for development testing.  Having said that, I'll fix it to only seed the filesystem project dir with content if it's not there.

**Comment by Pomax** [comment]
aye, that's what I was using
