### ISSUE TITLE
Hack thimble to conceal the brackets editor until it's fully loaded

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#42]
I'm not sure that there's a sane way to get brackets to load with panels hidden, rather than load with all of them visible and the user has to watch some disappear. Instead, I'm thinking Thimble should hide brackets as it loads and reveal it when it receives a postMessage from our `HideUI` extension saying "everything's ready!"

**Comment by humphd** [comment]
That's an interesting idea.  Let's try it and see what it feels like.

**Comment by sedge** [comment]
My experimentation so far: 

http://jsfiddle.net/h23ydzue/2/

**Comment by sedge** [comment]
http://jsfiddle.net/h23ydzue/5/
