### ISSUE TITLE
hosted.html - deleting all files, then dropping in new files, leaves bramble in a failed state

### ISSUE THREAD

**Issue by Pomax** [humphd/brackets#420]
the file dropping works file, but I have to hard-reload the tab in order for the live preview to then actually work again.

**Comment by humphd** [comment]
That's wrong, it should work.  Have you got my commits from earlier today there?  Which browser?  Can you screenshot and show me your console when that happens?

**Comment by Pomax** [comment]
I'll try to get some STR once I'm at a lull in actually writing code again

**Comment by humphd** [comment]
I'm pretty sure this is fixed, closing.
