### ISSUE TITLE
some cmd/ctrl-... commands gets intercepted rather thatn being passed to the browser (T, L)

### ISSUE THREAD

**Issue by Pomax** [humphd/brackets#421]
This seems a little too liberal when it comes to key interception. Especially if I can't use a mouse for a bit (or forever, if I have a hindrance or disability) but am 100% capable of using a keyboard, I expect cmd/ctrl-T and cmd/ctrl-L to be honoured by the browser, to get me to a new tab and get me into the URL bar, respectively

**Comment by humphd** [comment]
Likely reading around https://github.com/adobe/brackets/blob/7beb2cdbb1b4ddda1a6ae17a9caba481af54a45c/src/command/KeyBindingManager.js will help with this.

**Comment by errietta** [comment]
@Pomax @humphd which browser and keybindings is this reproducable on? On Chrome (ChromeOS) I can ctrl-T, ctrl-shift-t, ctrl-r, and other ctrl-shortcuts on my browser.

**Comment by Pomax** [comment]
this might require testing with the cursor in several different places (nside an element tag, as well as inside a regular text block, for instance) as the -T and -L keyboard shortcuts can be contextual.

base load:

Windows Firefox: ctrl-T works, ctrl-L works.
Windows Chrome: ctrl-T works, ctrl-L gets intercepted but does "nothing".
Windows IE11: both work fine

with the cursor in the document:

Windows Firefox: both ctrl-T and ctrl-L get intercepted
Windows Chrome: ctrl-T gets through, but ctrl-L gets intercepted
Windows IE 11: ctrl-L gets intercepted, ctrl-T *amazingly* reloads the tab instead of opening a new tab (what?)

Also the ctrl-W override to "close a file" rather than to close the tab in the browser is an interesting problem - on the one hand it makes sense, you don't want to accidentally close Thimble, but then there are mechanism to prevent accidental in-tab navigation, and overloading that shortcut might also be bad. @humphd, thoughts on that particular one?

**Comment by shadowcat-mst** [comment]
Ctrl-W is my bugbear - stopping me from closing a tab does *not* make me happy, I normally only expect that behaviour from spam/scam sites.

**Comment by humphd** [comment]
Here's a list of what I think I should do (I'm using CMD below to mean "CMD on Mac" and "CTRL on Win/Linux").  Let me know if you disagree or want to do something else.

Brackets Key Bindings to be removed in favour of browser shortcuts:
* CMD+O = File > Open (we have no file dialogs)
* CMD+N = File > New (we should let the user open a new window vs. a new file)
* CMD+W = File > Close (we should let the user close the tab vs. file)

Questions:
* CMD+ +, -, 0 = View > Increase/Decrease/Restore Font Size.  Do we want to only have this affect the editor, or let the browser apply it everywhere?
* CMD+T = Navigate > Quick Find Definition --> what to rebind this to?
* CMD+K = Navigate > Quick Docs --> what to rebind this to?
* CMD+L = Navigate > Go To Line --> what to rebind this to or just remove?

**Comment by humphd** [comment]
Also, https://github.com/humphd/brackets/blob/bramble/src/base-config/keyboard.json is the complete list, in case you can spot other problems in there that I've missed.

**Comment by Pomax** [comment]
I'm wondering if the [cmd-B + letter] concept makes sense, where the initial cmd-B makes keylistens go into "application keys" mode, so:

cmd-T: new tab, cmd-B-T: quick find definition
cmd-L: focus on url bar, cmd-B-L: go to line (...)

On the one hand, that's more "techy" but we currently don't advertise these keybindings at all, so the fact that they even kick in is probably worse than them not working if you're "guessing" they work based on having Brackets before on the desktop?

**Comment by humphd** [comment]
I'm an emacs user, so 15-step keybindings are fine with me, but I suspect I'm not the target user here :).  What about using ALT+L, ALT+T, etc. and just avoid cmd/ctrl for these few overlapping ones?

**Comment by Pomax** [comment]
that sounds like a decent plan. On windows, though, alt-... combinations can act as hotkeys for the (well hidden) old school file/edit/... menu system, so the following combinations would probably be fine to intercept, as long as we don't intercept just "alt" so that for accessibility people still *can* get into the menu system

**Comment by flukeout** [comment]
Wanted to leave a comment here about switching the file being edited, which is the main keyboard shortcut that I'm missing...

I'd like to propose
*  ``Command`` + ``Alt`` + ``Up`` = file above the currently edited one in the file view
*  ``Command`` + ``Alt`` + ``Down`` = file below the currently edited on

The default in the Brackets desktop editor is, ``Command`` + ``Shift`` + ``[`` or ``]`` - which also switches tabs in the browser.

ping @humphd

**Comment by Pomax** [comment]
oh wow. Yeah I'm up for that change!
