### ISSUE TITLE
Code using Path.extname() should deal with lower vs. upper case

### ISSUE THREAD

**Issue by Pomax** [humphd/brackets#427]
I zipped up a project I was working on, using ye olde pkzip, and then dragged it to bramble, and letting go with it hovered over the file bar. Instead of unpacking, it simply added it to my files list, and this seems... wrong?

**Comment by humphd** [comment]
Odd. Can you put the file somewhere so I can debug? What was the filename?

On Aug 17, 2015 9:07 PM, Mike Kamermans <notifications@github.com> wrote:

I zipped up a project I was working on, using ye olde pkzip, and then dragged it to bramble, and letting go with it hovered over the file bar. Instead of unpacking, it simply added it to my files list, and this seems... wrong?

**Comment by Pomax** [comment]
put the file online as http://pomax.nihongoresources.com/downloads/quick-glyph-maker.ZIP

**Comment by humphd** [comment]
```js
> require('path').extname('quick-glyph-maker.ZIP')
'.ZIP'
```
All caps, which messes with my check for special file types:

```js
                // Special-case .zip files, so we can offer to extract the contents
                if(Path.extname(filename) === ".zip") {
                    handleZipFile(deferred, file, filename, buffer, encoding);
                } else if(Path.extname(filename) === ".tar") {
                    handleTarFile(deferred, file, filename, buffer, encoding);
                } else {
                    handleRegularFile(deferred, file, filename, buffer, encoding);
                }
```

I can make it case insensitive.  There's actually some other places I should do that, so I'll morph this ticket.

**Comment by Pomax** [comment]
since we're dropping binary data anyway, is there a content type detection module we can tap into that works irrespective of extension? (something that examines the first 20 bytes and is able to go "this is a JPG", "this is a zip file", "this is an opentype font", etc?)

**Comment by humphd** [comment]
We don't have this, no; but someone could write it.  In the general case of being given a file path (without the data), and having to do this, you incur the overhead of having to read the whole file into memory, which sucks (we can't just grab the first 20 bytes...yet, until browsers get stream support).  In the drag-and-drop case, we do get a tip from the browser/OS in the form of the `FileReader` giving us a `File` with a `.type` property, http://www.w3.org/TR/FileAPI/#dfn-FPtype.  I use this now to try and sniff out text data vs. binary, but we could maybe try and look for other mime types.

I think the file extension mapping plan isn't horrible, though.  And my fix in the PR for this makes it work for upper/lower case, expanding our accuracy.
