### ISSUE TITLE
Remove any unnecessary connection and message events from PostMessageTransport.js

### ISSUE THREAD

**Issue by K-LV** [humphd/brackets#45]
Remove any unnecessary connection and message events from the PostMessageTransport.js file, located in the brackets-browser-livedev extension.

**Comment by gideonthomas** [comment]
@K-LV any update on this?

**Comment by K-LV** [comment]
Yes. I discovered that the "connect" and "message" events weren't being triggered in my PostMessageTransport.js file at all, in [here] (https://github.com/K-LV/brackets-browser-livedev/blob/master/lib/PostMessageTransport.js#L42) and [here] (https://github.com/K-LV/brackets-browser-livedev/blob/master/lib/PostMessageTransport.js#L56). I fixed this [here] (https://github.com/K-LV/brackets-browser-livedev/blob/removeEvents/lib/PostMessageTransport.js#L42) so they now trigger properly. However, it fails to trigger the [ConnectionConnect] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js#L156) event. This is where I'm stuck, I'm not sure how to make the ConnectionConnect event trigger properly.

**Comment by sedge** [comment]
Assigned to @K-LV

**Comment by AJDBenner** [comment]
[This](https://github.com/humphd/brackets-browser-livedev/pull/34) PR fixes this.
