### ISSUE TITLE
Brackets not loading

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#464]
the LinkManager patch seems to break on production with:
![screen shot 2015-09-15 at 11 22 47 am](https://cloud.githubusercontent.com/assets/5816130/9881009/23d7806e-5b9c-11e5-9713-ffb1bdeb9bbc.png)

**Comment by humphd** [comment]
This looks like bad cache, I can't reproduce anywhere.

**Comment by gideonthomas** [comment]
Yep
