### ISSUE TITLE
Add automatic colour palette extraction to the Image Viewer

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#466]
The built-in Image Viewer is cool, and mostly useless.  It shows you the file, and some basic size info:

![screenshot 2015-09-15 21 26 13](https://cloud.githubusercontent.com/assets/427398/9894322/71f750fe-5bf0-11e5-8fb5-3b6c7ee1afa1.png)

It would be nice if it offered some useful tools to the user.  One idea would be to have it show you the main colours in the current image.  We could use http://jariz.github.io/vibrant.js/ to do it.

The code for this lives in:
* https://github.com/humphd/brackets/blob/bramble/src/htmlContent/image-view.html
* https://github.com/humphd/brackets/blob/bramble/src/editor/ImageViewer.js

Extracting the colour swatches looks pretty simple:

```js
var img = document.createElement('img');
img.setAttribute('src', 'examples/octocat.png')

img.addEventListener('load', function() {
    var vibrant = new Vibrant(img);
    var swatches = vibrant.swatches()
    for (swatch in swatches)
        if (swatches.hasOwnProperty(swatch) && swatches[swatch])
            console.log(swatch, swatches[swatch].getHex())

    /*
     * Results into:
     * Vibrant #7a4426
     * Muted #7b9eae
     * DarkVibrant #348945
     * DarkMuted #141414
     * LightVibrant #f3ccb4
     */
});
```

Probably the code would need to go somewhere in the `onload` for the `img` in here: https://github.com/humphd/brackets/blob/bramble/src/editor/ImageViewer.js#L120-L149

**Comment by errietta** [comment]
hi @humphd I'm interested - is there a design of how it should look like if we do add this?

**Comment by errietta** [comment]
@gideonthomas 
16:52 < errietta> gthomas: ok i'm working on https://github.com/humphd/brackets/issues/466
16:53 < errietta> gthomas: so far i have https://github.com/errietta/brackets/tree/errietta/466
16:53 < errietta> i added Vibrant and did vibrant = new Vibrant(..) but it says Vibrant isn't a function
16:53 < errietta> although i can see vibrant.js being loaded

I logged console.log(Vibrant) and it's undefined :open_mouth:

**Comment by humphd** [comment]
@errietta I pulled your branch to test (btw, I'd caution against using numeric names for branches--I've been burned before by this where the number overlaps with the first digits of a commit SHA, use `issue466` or some other word prefix).  It looks to me like they have buggy code for doing the requirejs module wrapping.  I notice that `Vibrant` is `undefined` like you said (i.e., local variable in that module), but `window.Vibrant` exists.  So they are attaching it to the global instead of doing module loading.  For now, why don't you try building the rest of your prototype with `window.Vibrant` and we can send them a patch upstream if we decide to use their lib.

**Comment by errietta** [comment]
20:31 < errietta> it works fine
20:31 < errietta> but the thing is, the elements i'm generating with the colours are going underneath the image
20:31 < errietta> and i think i'm going to have to mess with lots of stuff's positioning to fix it
20:31 < errietta> D:
20:32 < errietta> also
20:32 < errietta> i tried with creating elements and appending them rather than doing strings
20:32 < errietta> but i had a really really weird result
20:32 < errietta> being http://imgur.com/CuEoYv9
20:34 < errietta> but yeah i'm more concerned about where to put that info
20:34 < errietta> elemnt wise

**Comment by humphd** [comment]
```
16:15 <~humph> errietta: it's neat how fast it is, eh?
16:19 <~humph> errietta: I'd do basically the same as they do here:
               http://jsfiddle.net/oskar/3479gj9e/light/
16:20 <~humph> put the <spans> directly in the html for the image viewer vs.
               doing a dynamic string
16:20 <~humph> we probably need to also figure out some way to show the hex as
               string, so <span> for circle but also some text below or
               something
```

**Comment by errietta** [comment]
@humphd got it working now https://github.com/humphd/brackets/pull/478

need design from @flukeout :smile:
