### ISSUE TITLE
Remove crosshair from image view

### ISSUE THREAD

**Issue by errietta** [humphd/brackets#487]
" Is there any way to get rid of the crosshairs with x & y coordinates when you hover over the image? It makes it seem like you can something to the image like select an area or crop it."

**Comment by errietta** [comment]
https://github.com/humphd/brackets/pull/501 @humphd  R?

PS: the selfie tool makes image-related bugs 10 times more fun
![selfie](https://cloud.githubusercontent.com/assets/134585/11168788/7d0ce540-8b97-11e5-9ab5-f0a907c436d3.png)

**Comment by humphd** [comment]
Landed
