### ISSUE TITLE
PostMessageTransport: Error parsing message: process-tick

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#50]
The live preview postMessage stuff is failing on a `process-tick` message that's being sent from somewhere:

```
PostMessageTransport: Error parsing message: process-tick:8000/extensions/default/brackets-browser-livedev/lib/PostMessageTransport.js:37
```

**Comment by sedge** [comment]
@humphd What are the steps to reproduce this? Does this occur even when the preview stuff appears to be working?

**Comment by humphd** [comment]
I get it on startup after I pulled down the latest bramble branch stuff.
