### ISSUE TITLE
Can no longer move files

### ISSUE THREAD

**Issue by errietta** [humphd/brackets#500]
as of cd407a7ecbf5df1226912a329457c6bb02db0eb6, I get an error when I right click a file and click 'move to'

TypeError: g[o.method] is undefined bramble.js:4:709

(Unfortunately that's the minified file, any idea how to see where the true error is?)

**Comment by humphd** [comment]
I can't reproduce this.  Can you give me your steps to reproduce?

**Comment by errietta** [comment]
@humphd

- Start new project
- Right click files pane, click 'new folder'
- Right click one of the files, click 'move to..'
No prompt to move to folder, instead just errors.

**Comment by errietta** [comment]
@humphd https://www.youtube.com/watch?v=W4nlkwiXAic

**Comment by errietta** [comment]
argh, my bad, had forgotten to run grunt build-browser :stuck_out_tongue_winking_eye:
