### ISSUE TITLE
Deploy super-thimble somewhere accessible for testing

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#51]
Our modified thimble is ready to be deployed. Ideally, it wouldn't be deployed into Webmaker proper, because we can't devote time to automating the process yet. 

We were thinking heroku, and we need to know how best to make it usable. Can we hook it up to the rest of webmaker with environment variables? Can it stand alone without webmaker-core? 

cc: @Pomax

**Comment by Pomax** [comment]
it'll work fine on Heroku as a content creator without make publication, *but* your heroku instance will need to be running with a database addon, because the sqlite writing it does is lost when the stub is powered down (it just restarts the stub, instead of saving the filesystem on shutdown).
