### ISSUE TITLE
editing just a single file

### ISSUE THREAD

**Issue by danielzfranklin** [humphd/brackets#512]
I have an existing setup that uses codemirror to allow editing of stored code. I would like to replace codemirror with Bramble to allow better and more featureful editing. However, I would not like to have Bramble manage an entire filesystem for me, just pass it a string for what I want to appear in the editor and then read out a string of the edited file. Can this be done?

Thank you,
Daniel

**Comment by humphd** [comment]
That's basically what I do here:

* https://github.com/humphd/brackets/blob/bramble/src/hosted.html
* https://github.com/humphd/brackets/blob/bramble/src/hosted.js

All you need to do is write that one file and then tell Bramble to mount it.

**Comment by danielzfranklin** [comment]
This project looks amazing! Thanks for all your work. Sorry for the stupid question.
