### ISSUE TITLE
`npm install` doesn't work

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#513]
Node version: 5.0.0
npm version: 3.3.6

When trying to install deps with the above node version, it gets stuck here:
```
> node install.js

Download already available at /var/folders/zk/0v_5l8190rq57jdt5pxccpxc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/gideon/Mozilla/brackets/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/zk/0v_5l8190rq57jdt5pxccpxc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1451943582893/phantomjs-1.9.8-macosx -> /Users/gideon/Mozilla/brackets/node_modules/phantomjs/lib/phantom
```

When I downgrade my node version to 0.12, it works.

**Comment by humphd** [comment]
In addition to getting this working well in newer node in general, we should just dump the phantomjs dep, since it's only for running the brackets tests, which we don't do.

**Comment by gideonthomas** [comment]
This seems to also be an issue with node 4.2

**Comment by gideonthomas** [comment]
Apparently I can't `grunt build-browser` anymore either -.-
Ok I'll remove the phantomjs dep
