### ISSUE TITLE
Combine `thimbleProxy`, `HideUI` and  `brackets-browser-livedev`

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#55]
There isn't a strong reason to keep them separate, and they're coupled together anyway.

**Comment by humphd** [comment]
We should consider if other extensions we're doing could be added into that too.

**Comment by gideonthomas** [comment]
assigned to @AJBenner

**Comment by AJDBenner** [comment]
@sedge @gideonthomas  this issue has been resolved with [this](https://github.com/humphd/brackets-browser-livedev/pull/27) PR
