### ISSUE TITLE
Replace current brackets instance within heroku deployment with dist

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#59]
Presently with our distribution on heroku, we are deploying brackets in unbulit form from the src/ of brackets, what we need to do is to grunt build and deploy brackets from dist

**Comment by sedge** [comment]
Ideally, three things need to happen:

1. A branch for our "super thimble" needs to be created 
2. We need to publish `bramble`'s dist folder as a module on npm
3. We need to patch the super thimble branch to use it.
