### ISSUE TITLE
Connect Thimble UI to Brackets commands

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#62]
There are a few Thimble UI bits that we need to connect to Brackets, specifically the Undo, Redo, Size, and reload buttons.  Doing this would involve having the `onclick` for these cause a message to be sent to the Brackets iframe window, and then have that event get consumed by thimbleProxy such that it fired the correct command in the Brackets instance.  You can probably steal code from the Brackets menu, which fires commands for these things when you click on the menu items.

Later we can expose other features via some kind of menu system in Thimble.  This will be the start.

**Comment by KeniMorri** [comment]
Alright, I'll see what I can do.

**Comment by gideonthomas** [comment]
Assigned to @KeniMorri

**Comment by sedge** [comment]
@KeniMorri Can you link to the PRs?

**Comment by KeniMorri** [comment]
Added Listener in thimble proxy in PR's AJDBenner/thimbleProxy: 
https://github.com/AJDBenner/thimbleProxy/pull/13
https://github.com/AJDBenner/thimbleProxy/pull/11
Updated Brackets to latest version of that submodule in here:
https://github.com/humphd/brackets/pull/77
https://github.com/humphd/brackets/pull/76
And Added postMessageTransport to thimble proxy within bramble proxy:
https://github.com/sedge/thimble.webmaker.org/pull/8
https://github.com/sedge/thimble.webmaker.org/pull/5

**Comment by gideonthomas** [comment]
@KeniMorri is this fixed?

**Comment by KeniMorri** [comment]
Yesh
