### ISSUE TITLE
Don't console.log every postMessage transport event we receive in preview iframe

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#63]
Right now we're printing a ton of diagnostic crap in the iframe preview window, basically every time we get a message from the editor window via the postMessage transport.  There's really no need for this at this point.  Let's get rid of that so the console is less noisy.

**Comment by AJDBenner** [comment]
@humphd This issue can be closed. It was fixed with this PR https://github.com/humphd/brackets-browser-livedev/pull/23
