### ISSUE TITLE
Get our heroku deployment to integrate with webmaker

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#65]
Super thimble isn't playing nice with the rest of webmaker staging. In particular, we get a 403 error whenever `/verify` is hit on the super-thimble domain. This is a login.wm.o error.

**Comment by sedge** [comment]
Integration with heroku's login server now works.

**Comment by humphd** [comment]
Nice.

**Comment by sedge** [comment]
At this point, publishing is broken and I'm following up with a couple of the core webmaker engineers to get the proper credentials to fix this.

**Comment by humphd** [comment]
FYI, I've filed a bug upstream in Thimble to figure out full deployment, too:

https://github.com/mozilla/thimble.webmaker.org/issues/474

**Comment by sedge** [comment]
Fantastic. We've hit a wall on this, since I'd need a dedicated domain to make `make-valet` work on heroku. Cuz reasons haha

**Comment by sedge** [comment]
Blocked on @jbuck getting a heroku deployment working with Webmaker's staging suite

**Comment by sedge** [comment]
Closed with https://github.com/mozilla/thimble.webmaker.org/issues/474
