### ISSUE TITLE
Develop a solution to integrate/create Thimble's tutorial feature in Bramble

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#67]
Thimble has a neat [tutorial feature](https://thimble.webmaker.org/project/45564/remix) that we need to implement in Bramble to maintain parity with Thimble.

We need to figure out how to do this i.e. 
* whether we can use most of existing Thimble code or 
* implementing it from scratch or
* a combination of the two

**Comment by gideonthomas** [comment]
also assigned to @AJDBenner

**Comment by sedge** [comment]
The mechanism behind this is pretty interesting.

Thimble "makes" have tags, little pieces of metadata that can help filter makes. A tutorial is simply a separate thimble make that is connected to a thimble project by including a special tag that includes a link to the make that will be the tutorial.

This system needs to be adapted, and I figure it could work in one of two ways:

1.  We allow thimble to use it's own tutorial pane, and set up a more sophisticated postmessage proxy between it and brackets to allow the more advanced tutorial features (like jumping to a line in the code from a link in the tutorial) This is probably the simplest implementation
2.  We use the same mechanism thimble uses to load a tutorial if it exists, and postMessage it to a brackets extension that creates a pane inside brackets itself.

**Comment by sedge** [comment]
For more details on this, see https://support.mozilla.org/en-US/kb/thimble-tutorials

**Comment by gideonthomas** [comment]
@sedge who creates these makes?

Do we need the "Publish" feature to be implemented in Bramble for this to work so that custom makes can be used as tutorials? Or is that out of scope?

**Comment by sedge** [comment]
Anyone can create a tutorial, but it is a two step process. 

1. Create a thimble make that will be the tutorial
2. Create the make that the tutorial will guide the user through.

Check the link I posted for more details.

**Comment by humphd** [comment]
The tutorials also include some custom JS to do line highlighting in the editor when you hover over certain things in the tutorial text.  I don't know how it was doing that, but probably by talking directly to the CodeMirror instance or using postMessage?  Look into that, too.

I'd copy what https://github.com/gruehle/MarkdownPreview does and use a split panel in the editor.  You can probably load the tutorial in there and then talk back and forth with the editor over postMessage in your extension.

**Comment by sedge** [comment]
The tutorials were communicating directly with the CodeMirror instance, which is why I think we can probably just proxy those commands to the brackets CodeMirror instance as a shortcut to getting this working. Is that too much of a quick fix?

**Comment by humphd** [comment]
Do what works for a first attempt.

**Comment by gideonthomas** [comment]
Seems like we can use almost all of thimble's existing code. However, a few fixes need to be done:
* `Uncaught TypeError: undefined is not a function` needs to be fixed. It crashes [here](https://github.com/sedge/thimble.webmaker.org/blob/mvpIntegration/public/scripts/tutorials.js#L101). This can probably be fixed by using @sedge's fix above
* https://support.mozilla.org/en-US/kb/thimble-tutorials#w_controls-for-the-user shows that user control buttons need to exist, however, they cannot be seen (even in mozilla's thimble). They need to be made visible and their functionality tested.
