### ISSUE TITLE
Fix postMessageTransport to be able to reload the preview

### ISSUE THREAD

**Issue by sedge** [humphd/brackets#69]
See: https://github.com/adobe/brackets/blob/0ebf3737b8e2fba8c16dc839326338acd0aac2d2/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/LiveDevProtocolRemote.js#L226

LiveDev has the ability to remotely cause the preview window (or iframe in our case) to reload, and we need to patch our implementation to cause this reload to pull in the state of the document being previewed.

**Comment by sedge** [comment]
@K-LV Anything to add?

**Comment by sedge** [comment]
https://github.com/humphd/brackets-browser-livedev/pull/28/files

**Comment by K-LV** [comment]
I've updated my [PR] (https://github.com/humphd/brackets-browser-livedev/pull/28/files) to include support for multiple files

**Comment by K-LV** [comment]
**Update**
I've been looking at the way regular Brackets handles CSS files. This is what I've found so far:
* When a CSS file is added to a Live HTML Document it should trigger the "StylesheetAdded" event. 
![screen shot 2015-03-16 at 4 19 17 pm](https://cloud.githubusercontent.com/assets/9330361/6675632/69cabb24-cbf8-11e4-9f0a-b2468a415a0c.png)
* The event is picked up [here] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/LiveDevMultiBrowser.js#L574) which then calls the _styleSheetAdded function and adds it to the _relatedDocuments array.
* When the document is loaded for the first time 
![screen shot 2015-03-16 at 4 28 21 pm](https://cloud.githubusercontent.com/assets/9330361/6675794/82eebaa0-cbf9-11e4-95e2-b11317d2943b.png)
or when you switch over to a document that already has an external CSS linked to it, it triggers the "DocumentRelated" event.
![screen shot 2015-03-16 at 4 27 20 pm](https://cloud.githubusercontent.com/assets/9330361/6675777/5f3f867a-cbf9-11e4-85ba-a27ac902f61f.png)
* That is picked up [here] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/LiveDevMultiBrowser.js#L566) and the _styleSheetAdded function is called again.
* It appears the [DocumentObserver] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/DocumentObserver.js#L173) is where it sends the "StylesheetAdded" message through the transport.
* And [this] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/DocumentObserver.js#L301) is where the "DocumentRelated" message is sent.
* The Document Observer is called by the [LiveDevProtocolRemote] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/LiveDevProtocolRemote.js#L271)

Our code only triggers the "Runtime.evalute" event, sent from the LiveDevProtocol [here] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js#L238) and the "Page.navigate" event [here] (https://github.com/humphd/brackets/blob/bramble/src/LiveDevelopment/MultiBrowserImpl/protocol/LiveDevProtocol.js#L316).
![screen shot 2015-03-16 at 4 36 29 pm](https://cloud.githubusercontent.com/assets/9330361/6676462/544f8f1c-cbfe-11e4-96fe-0b9c75829e85.png)
I'm not sure why our code doesn't call on the "DocumentRelated" or "StylesheetAdded" events.

**Comment by humphd** [comment]
Is this just something that's missing from the MultiBrowser LiveDev stuff (i.e., does Brackets have it in the full LiveDev code)?

**Comment by humphd** [comment]
Depends on #115. Moving out of PPP.

**Comment by gideonthomas** [comment]
Fixed with ce9a45d41c72739c8b779a0fb63f113a12416c1b

**Comment by K-LV** [comment]
That commit lies in the extension brackets-browser-livedev [here] (https://github.com/humphd/brackets-browser-livedev/commit/ce9a45d41c72739c8b779a0fb63f113a12416c1b); part of this [PR] (https://github.com/humphd/brackets-browser-livedev/pull/45).
