### ISSUE TITLE
Fix HTMLHinter to work properly in the browser

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#70]
Presently none of the functionality of HTMLHinter works in brackets within thimble, investigate this issue, and fix it.

**Comment by sedge** [comment]
@KeniMorri Can you add steps to reproduce?

**Comment by humphd** [comment]
Closable yet?

**Comment by gideonthomas** [comment]
fixed with 633bd75bde265dbcb5369f4c0c3b69113ff76b8f
