### ISSUE TITLE
Cannot open pre-made makes

### ISSUE THREAD

**Issue by gideonthomas** [humphd/brackets#71]
Currently, if you create a make and then publish it, then go to the URL for the make and click "Remix", it opens up the editor however, the content loaded in the editor is the default content and not the make's content itself.

https://github.com/humphd/brackets/issues/67 depends on this!

**Comment by gideonthomas** [comment]
@sedge comments?

**Comment by sedge** [comment]
Thimble pre-renders the thimble `index.html` [here](https://github.com/sedge/thimble.webmaker.org/blob/mvpIntegration/routes/index.js#L41-L79) by passing it all the relevant information.

Try to trace it from there all the way to [this code](https://github.com/sedge/thimble.webmaker.org/blob/mvpIntegration/public/friendlycode/js/friendlycode.js#L81-L98) to make sure the make's contents get through to where the editor tries to render it.

**Comment by sedge** [comment]
[This file](https://github.com/sedge/thimble.webmaker.org/blob/mvpIntegration/public/scripts/friendlycode.js) kicks off the process once `index.html` is loaded on the client, so it's another important step in the chain.
