### ISSUE TITLE
Fix Thimble x Brackets issue stemming from thimble undo/redo

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#84]
Presently when you delete certain portions of the code, you'll be met with an error in brackets live dev presented below:
![Example](https://dl.dropboxusercontent.com/u/26358556/Blog/Screenshot%202015-03-09%2011.20.18.png)

Will continue updating this post.

**Comment by humphd** [comment]
I wonder if this is really an error we care about: a node in the DOM that was there isn't anymore, so it can't be selected.  It seems like a somewhat normal case for nodes to disappear, when they are being live edited.

**Comment by sedge** [comment]
wontfix
