### ISSUE TITLE
Remove the quickdocs extension

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#87]
According to https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#quick-edit (see the section on Quick Docs), you should be able to use Cmd+K or Ctrl+K to get documentation for the bit of html or css that you're mouse is sitting over.  When I try, I see:
```
Unable to load CSS documentation database:  NotFoundmain.js:69
(anonymous function)jquery-2.1.3.min.js:2
n.Callbacks.jjquery-2.1.3.min.js:2 
n.Callbacks.k.fireWithjquery-2.1.3.min.js:2 
n.extend.Deferred.n.each.e.(anonymous function)FileUtils.js:85 
(anonymous function)File.js:112 
(anonymous function)FilerFileSystem.js:194 
(anonymous function)filer.js:6407 
completefiler.js:5615 
(anonymous function)filer.js:4466 
read_directory_datafiler.js:4126 
read_parent_directory_datafiler.js:4126 
read_parent_directory_datafiler.js:4126 
read_parent_directory_datafiler.js:4141 
get_node_from_parent_directory_datafiler.js:7066 
(anonymous function)filer.js:2263 (anonymous function)
```

The QuickDocs JSON is loaded lazily (i.e., only when you need it), and based on this stack, it looks like it's trying to get it directly from the filesystem.  On desktop, with regular Brackets and a real OS filesystem, this will work fine.  However, in the browser with Filer, we won't have that file in the fs at all.

Our options are to download the JSON files (there's probably more than one we need) in the background after the app starts if it's not already there, so that it *will* be there when it's requested.  Right now we are using a RAM-backed filesystem, so it would mean having to do this every time.  Other options include moving these JSON files into the require bundle and loading with the `text` plugin, or removing this feature altogether.

The `css.json` file is 390K.  My vote is to rip this out, unless someone can figure out a solution.

**Comment by sedge** [comment]
This is a strong reason to switch from using RAM to using localstorage. It wouldn't need much tweaking filesystem-wise: we could still write the `index.html` file on every load of a thimble make, but the first time the storage is created the docs could be downloaded. We could even provide a prompt to ask the user if they'd like to? 

This is a cool feature for a learning tool IMO. I'd be happy to take this on when I'm done with the grunt stuff, if we can find an approach you like. Otherwise let's remove it.

**Comment by sedge** [comment]
Let's rip it out.

**Comment by gideonthomas** [comment]
@sedge are we abandoning this?

**Comment by humphd** [comment]
Yes, we're going to drop this for now.
