### ISSUE TITLE
Fix odd multi-file error that duplicates current doc into preview window

### ISSUE THREAD

**Issue by KeniMorri** [humphd/brackets#91]
Presently with multi-files, if we create another file, then return to index.html any keys pressed within brackets will duplicate whatever is in the preview window, presented below in a screen shot and video:
![screenshot 2015-03-11 10 39 03](https://cloud.githubusercontent.com/assets/1750230/6598570/f3ba7fbc-c7da-11e4-8dad-72780a5c3965.png)
https://www.youtube.com/watch?v=oowVRR8IDZI&feature=youtu.be

**Comment by K-LV** [comment]
@KeniMorri I'm working on this, it's related to this [issue] (https://github.com/humphd/brackets-browser-livedev/pull/28)

**Comment by K-LV** [comment]
@KeniMorri upon further investigation, it appears that the [copy/paste] (https://github.com/adobe/brackets/pull/10653) patch fixes this issue.

**Comment by KeniMorri** [comment]
Fixed with copy/paste patch
