### ISSUE TITLE
Remove bottom margin/padding from editor iframe and/or Brackets status bar

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#94]
![screen shot 2015-03-12 at 10 43 11 am](https://cloud.githubusercontent.com/assets/427398/6620035/bee06412-c8a4-11e4-937e-dac0d10ff5fa.png)

There's a bit of unwanted margin or padding at the bottom of the editor iframe, or perhaps inside the editor itself.  You really notice it when the file view is open, and the colours contrast.  It would be nice to fix this.

**Comment by AJDBenner** [comment]
I'm looking into this issue

**Comment by AJDBenner** [comment]
I've noticed this error occurs in chrome and not firefox. Also, I believe it's being caused by the div in thimble with class="source-code" within thimble.

**Comment by AJDBenner** [comment]
This issue doesn't seem to be critical so we are removing it from the PPP milestone.

**Comment by K-LV** [comment]
Can confirm that this issue occurs in Chrome, Safari, and Opera but not in Firefox.

**Comment by humphd** [comment]
All of which are using WebKit or Blink vs. Gecko.  I wonder what IE does?

**Comment by humphd** [comment]
This has been fixed somehow by other changes, closing.
